from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from backlog_repo.outcomes import extract_outcome_markdown, upsert_outcome_markdown
from backlog_repo.plan_index import (
    archive_integrity_unknown_plan_ticket_file,
    archive_plan_ticket_file,
    dedupe_actioned_plan_ticket_files,
    dedupe_queued_plan_ticket_files_when_actioned_exists,
    reconcile_missing_plan_atoms,
    scan_plan_ticket_index,
    sync_atom_actions_from_plan_folders,
)


def _write_plan(path: Path, fingerprint: str, title: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"# {title}\n\n"
        f"- Fingerprint: `{fingerprint}`\n"
        "- Case ID: `case:archive-test`\n"
        "- Plan revision ID: `plan:archive-test:v1`\n",
        encoding="utf-8",
    )


def _write_generated_plan(path: Path, fingerprint: str, title: str) -> None:
    _write_plan(path, fingerprint, title)
    path.write_text(
        path.read_text(encoding="utf-8")
        + "\nGenerated by `python -m usertest_backlog.cli reports export-tickets`.\n",
        encoding="utf-8",
    )


def _passed(
    kind: str,
    reference: str,
    *,
    case_id: str,
    plan_revision_id: str,
    fingerprint: str,
) -> dict[str, object]:
    common = {
        "producer": "usertest_implement",
        "verification_producer": "runner_core",
        "evidence_kind": kind,
        "ticket_body_sha256": "c" * 64,
        "local_plan_sha256": "d" * 64,
        "local_plan_filename": "ticket.md",
        "verification_contract_sha256": "e" * 64,
        "target_contract_sha256": "1" * 64,
        "verified_implementation_head": "2" * 40,
        "fingerprint": fingerprint,
        "case_id": case_id,
        "plan_revision_id": plan_revision_id,
    }
    if kind == "test":
        receipt = {
            **common,
            "receipt_schema_version": 2,
            "run_dir": f"runs/{kind}",
            "verification_path": f"runs/{kind}/verification.json",
            "verification_sha256": "a" * 64,
            "ticket_ref_path": f"runs/{kind}/ticket_ref.json",
            "ticket_ref_sha256": "b" * 64,
            "verification_binding_sha256": "f" * 64,
            "commands": [f"verify-{kind}"],
        }
    else:
        receipt = {
            **common,
            "receipt_schema_version": 3,
            "role_artifact_path": f"runs/{kind}/outcome_role.json",
            "role_artifact_sha256": "a" * 64,
            "role_contract_sha256": "f" * 64,
            "merged_commit": "abc123",
        }
    return {
        "kind": kind,
        "reference": reference,
        "result": "passed",
        "runner_receipt": receipt,
    }


def test_queue_dedupe_archives_relationship_without_losing_plan(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "0123456789abcdef"
    name = f"20260709_{fingerprint}_archive-test.md"
    queued = owner_root / ".agents" / "plans" / "2 - ready" / name
    completed = owner_root / ".agents" / "plans" / "5 - complete" / name
    _write_generated_plan(queued, fingerprint, "Queued copy")
    _write_plan(completed, fingerprint, "Completed copy")

    assert dedupe_queued_plan_ticket_files_when_actioned_exists(owner_root=owner_root) == 1
    assert not queued.exists()
    assert completed.exists()

    archived = owner_root / ".agents" / "plans" / "6 - archived" / name
    assert archived.exists()
    outcome = extract_outcome_markdown(archived.read_text(encoding="utf-8"))
    assert outcome is not None
    assert outcome["state"] == "duplicate"
    assert outcome["related_case_id"] == "case:archive-test"
    assert outcome["related_fingerprint"] == fingerprint

    index = scan_plan_ticket_index(owner_root=owner_root)
    assert index[fingerprint]["paths"] == [str(completed)]
    assert index[fingerprint]["relationship_paths"] == [str(archived)]


def test_queue_dedupe_does_not_archive_idea_or_manual_copy(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "1010101010101010"
    name = f"20260709_{fingerprint}_protected.md"
    queued = owner_root / ".agents" / "plans" / "2 - ready" / name
    completed = owner_root / ".agents" / "plans" / "5 - complete" / name
    _write_plan(queued, fingerprint, "IDEA-005 Protected queue copy")
    queued.write_text(
        queued.read_text(encoding="utf-8")
        + "\nGenerated from tracked idea plan `.agents/plans/0 - roadmaps/IDEA-005.md`.\n",
        encoding="utf-8",
    )
    _write_generated_plan(completed, fingerprint, "Actioned generated copy")
    queued_bytes = queued.read_bytes()

    assert dedupe_queued_plan_ticket_files_when_actioned_exists(owner_root=owner_root) == 0
    assert queued.read_bytes() == queued_bytes
    assert completed.exists()


def test_actioned_dedupe_repairs_same_bucket_before_strict_index(
    tmp_path: Path,
) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "1111111111111111"
    complete = owner_root / ".agents" / "plans" / "5 - complete"
    first = complete / f"20260708_{fingerprint}_older-copy.md"
    second = complete / f"20260709_{fingerprint}_newer-copy.md"
    _write_generated_plan(first, fingerprint, "Older generated copy")
    _write_generated_plan(second, fingerprint, "Newer generated copy")

    with pytest.raises(ValueError, match="plan_index_multiple_canonical_copies"):
        scan_plan_ticket_index(owner_root=owner_root)

    assert dedupe_actioned_plan_ticket_files(owner_root=owner_root) == 1
    assert not first.exists()
    assert second.exists()
    index = scan_plan_ticket_index(owner_root=owner_root)
    assert index[fingerprint]["paths"] == [str(second)]
    assert len(index[fingerprint]["relationship_paths"]) == 1

    # Relationship copies are excluded from the raw repair candidate set, so
    # rerunning the repair is byte- and path-stable.
    before = {
        path: path.read_bytes()
        for path in (owner_root / ".agents" / "plans").rglob("*")
        if path.is_file()
    }
    assert dedupe_actioned_plan_ticket_files(owner_root=owner_root) == 0
    after = {
        path: path.read_bytes()
        for path in (owner_root / ".agents" / "plans").rglob("*")
        if path.is_file()
    }
    assert after == before


def test_actioned_dedupe_preserves_unknown_nul_copy_and_archives_only_generated(
    tmp_path: Path,
) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "2222222222222222"
    complete = owner_root / ".agents" / "plans" / "5 - complete"
    readable = complete / f"20260708_{fingerprint}_readable.md"
    corrupt = complete / f"20260709_{fingerprint}_nul.md"
    _write_generated_plan(readable, fingerprint, "Readable copy")
    corrupt.parent.mkdir(parents=True, exist_ok=True)
    original_corrupt_bytes = b"# historical plan\n\x00{unrelated batch json}\n"
    corrupt.write_bytes(original_corrupt_bytes)

    assert dedupe_actioned_plan_ticket_files(owner_root=owner_root) == 1
    assert not readable.exists()
    assert corrupt.read_bytes() == original_corrupt_bytes
    archived_matches = list(
        (owner_root / ".agents" / "plans" / "6 - archived").glob(f"*_{fingerprint}_readable*.md")
    )
    assert len(archived_matches) == 1
    archived = archived_matches[0]
    outcome = extract_outcome_markdown(archived.read_text(encoding="utf-8"))
    assert outcome is not None
    assert outcome["state"] == "duplicate"
    index = scan_plan_ticket_index(owner_root=owner_root)
    assert index[fingerprint]["paths"] == []
    assert index[fingerprint]["integrity_unknown_paths"] == [str(corrupt)]
    assert index[fingerprint]["relationship_paths"] == [str(archived)]


def test_actioned_dedupe_preserves_readable_manual_plan(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "2121212121212121"
    complete = owner_root / ".agents" / "plans" / "5 - complete"
    manual = complete / f"20260708_{fingerprint}_manual.md"
    generated = complete / f"20260709_{fingerprint}_generated.md"
    _write_plan(manual, fingerprint, "Manually authored plan")
    _write_generated_plan(generated, fingerprint, "Automated copy")
    manual_bytes = manual.read_bytes()

    assert dedupe_actioned_plan_ticket_files(owner_root=owner_root) == 1
    assert manual.read_bytes() == manual_bytes
    assert not generated.exists()
    index = scan_plan_ticket_index(owner_root=owner_root)
    assert index[fingerprint]["paths"] == [str(manual)]


def test_actioned_dedupe_never_mutates_idea_originated_plan(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "3333333333333333"
    complete = owner_root / ".agents" / "plans" / "5 - complete"
    idea = complete / f"20260708_{fingerprint}_idea.md"
    generated = complete / f"20260709_{fingerprint}_generated.md"
    _write_plan(idea, fingerprint, "IDEA-005 Preserve this plan")
    idea.write_text(
        idea.read_text(encoding="utf-8")
        + "\nGenerated from tracked idea plan `.agents/plans/0 - roadmaps/IDEA-005.md`.\n",
        encoding="utf-8",
    )
    _write_generated_plan(generated, fingerprint, "Automated copy")
    idea_bytes = idea.read_bytes()

    assert dedupe_actioned_plan_ticket_files(owner_root=owner_root) == 1
    assert idea.read_bytes() == idea_bytes
    assert not generated.exists()
    index = scan_plan_ticket_index(owner_root=owner_root)
    assert index[fingerprint]["paths"] == [str(idea)]


def test_actioned_dedupe_refuses_ambiguous_idea_duplicates(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "4444444444444444"
    complete = owner_root / ".agents" / "plans" / "5 - complete"
    paths = [complete / f"2026070{day}_{fingerprint}_idea-{day}.md" for day in (8, 9)]
    for path in paths:
        _write_plan(path, fingerprint, "IDEA-005 Preserve this plan")
        path.write_text(
            path.read_text(encoding="utf-8")
            + "\nGenerated from tracked idea plan `.agents/plans/0 - roadmaps/IDEA-005.md`.\n",
            encoding="utf-8",
        )
    before = {path: path.read_bytes() for path in paths}

    with pytest.raises(
        ValueError,
        match="Refusing automated repair of duplicate non-generated or unknown plans",
    ):
        dedupe_actioned_plan_ticket_files(owner_root=owner_root)
    assert {path: path.read_bytes() for path in paths} == before


def test_actioned_dedupe_preflights_unknown_ambiguity_before_any_write(
    tmp_path: Path,
) -> None:
    owner_root = tmp_path / "repo"
    complete = owner_root / ".agents" / "plans" / "5 - complete"

    repairable_fingerprint = "5555555555555555"
    generated_paths = [
        complete / f"2026070{day}_{repairable_fingerprint}_generated-{day}.md" for day in (8, 9)
    ]
    for path in generated_paths:
        _write_generated_plan(path, repairable_fingerprint, "Generated duplicate")

    ambiguous_fingerprint = "6666666666666666"
    manual = complete / f"20260708_{ambiguous_fingerprint}_manual.md"
    corrupt = complete / f"20260709_{ambiguous_fingerprint}_unknown.md"
    _write_plan(manual, ambiguous_fingerprint, "Manual protected plan")
    corrupt.write_bytes(b"# unknown\n\x00cannot classify provenance\n")
    all_paths = [*generated_paths, manual, corrupt]
    before = {path: path.read_bytes() for path in all_paths}

    with pytest.raises(
        ValueError,
        match="Refusing automated repair of duplicate non-generated or unknown plans",
    ):
        dedupe_actioned_plan_ticket_files(owner_root=owner_root)
    assert {path: path.read_bytes() for path in all_paths} == before
    assert not (owner_root / ".agents" / "plans" / "6 - archived").exists()


@pytest.mark.parametrize(
    "payload",
    [
        b'"""Identity AST transform test cases"""\n\nfrom mypy import build\n',
        b'{"batch_id":"unrelated"}\n{"status":"failed"}\n',
        b"# plausible prefix\n\x00unrelated batch output\n",
        b"# invalid utf8\n\xff\xfe historical bytes\n",
    ],
    ids=["unrelated-mypy-python", "json-prefix", "nul", "invalid-utf8"],
)
def test_explicit_integrity_archive_preserves_untrusted_bytes(
    tmp_path: Path,
    payload: bytes,
) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "1010101010101010"
    source = (
        owner_root
        / ".agents"
        / "plans"
        / "5 - complete"
        / f"20260210_{fingerprint}_semantic-corruption.md"
    )
    source.parent.mkdir(parents=True)
    source.write_bytes(payload)
    source_sha256 = hashlib.sha256(payload).hexdigest()

    archived = archive_integrity_unknown_plan_ticket_file(
        owner_root=owner_root,
        path=source,
        reason="Historical plan path contains unrelated content",
        expected_source_sha256=source_sha256,
    )

    assert not source.exists()
    assert archived.read_bytes() == payload
    sidecar = archived.with_suffix(f"{archived.suffix}.outcome.json")
    outcome = json.loads(sidecar.read_text(encoding="utf-8"))
    assert outcome["state"] == "integrity_unknown"
    assert outcome["outcome_scope"] == "plan_copy"
    assert outcome["intended_disposition"] == "unverified"
    assert outcome["integrity_reason"] == "Historical plan path contains unrelated content"
    assert outcome["previous_path"] == str(source.resolve())
    assert outcome["original_sha256"] == source_sha256
    assert outcome["archive_sha256"] == source_sha256

    index = scan_plan_ticket_index(owner_root=owner_root)
    assert index[fingerprint]["status"] == "integrity_unknown"
    assert index[fingerprint]["paths"] == []
    assert index[fingerprint]["integrity_unknown_paths"] == [str(archived)]


def test_semantic_integrity_archive_cannot_promote_atom_or_displace_canonical_plan(
    tmp_path: Path,
) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "2020202020202020"
    atom_id = "usertest/20260709T000000Z/codex/0:suggested_change:9"
    canonical = (
        owner_root / ".agents" / "plans" / "5 - complete" / f"20260211_{fingerprint}_canonical.md"
    )
    corrupt = canonical.with_name(f"20260210_{fingerprint}_corrupt.md")
    _write_plan(canonical, fingerprint, "Readable canonical plan")
    corrupt.write_text(
        f"from __future__ import annotations\n# unrelated `{atom_id}`\n",
        encoding="utf-8",
    )
    corrupt_bytes = corrupt.read_bytes()

    archived = archive_integrity_unknown_plan_ticket_file(
        owner_root=owner_root,
        path=corrupt,
        reason="Valid UTF-8 contains unrelated Python source",
        expected_source_sha256=hashlib.sha256(corrupt_bytes).hexdigest(),
        archive_reason="Corrupt duplicate of the retained canonical plan",
        related_fingerprint=fingerprint,
        related_case_id="case:archive-test",
        related_plan_revision_id="plan:archive-test:v1",
    )
    assert (
        archive_integrity_unknown_plan_ticket_file(
            owner_root=owner_root,
            path=archived,
            reason="Valid UTF-8 contains unrelated Python source",
            expected_source_sha256=hashlib.sha256(corrupt_bytes).hexdigest(),
            archive_reason="Corrupt duplicate of the retained canonical plan",
            related_fingerprint=fingerprint,
            related_case_id="case:archive-test",
            related_plan_revision_id="plan:archive-test:v1",
        )
        == archived
    )
    sidecar = archived.with_suffix(f"{archived.suffix}.outcome.json")
    sidecar_bytes = sidecar.read_bytes()
    with pytest.raises(ValueError, match="Conflicting integrity archive sidecar"):
        archive_integrity_unknown_plan_ticket_file(
            owner_root=owner_root,
            path=archived,
            reason="Valid UTF-8 contains unrelated Python source",
            expected_source_sha256=hashlib.sha256(corrupt_bytes).hexdigest(),
            archive_reason="Corrupt duplicate of the retained canonical plan",
            related_fingerprint="2121212121212121",
            related_case_id="case:archive-test",
            related_plan_revision_id="plan:archive-test:v1",
        )
    assert archived.read_bytes() == corrupt_bytes
    assert sidecar.read_bytes() == sidecar_bytes

    assert dedupe_actioned_plan_ticket_files(owner_root=owner_root) == 0
    assert dedupe_actioned_plan_ticket_files(owner_root=owner_root) == 0
    index = scan_plan_ticket_index(owner_root=owner_root)
    assert index[fingerprint]["status"] == "actioned"
    assert index[fingerprint]["paths"] == [str(canonical)]
    assert index[fingerprint]["integrity_unknown_paths"] == [str(archived)]
    integrity_record = index[fingerprint]["integrity_unknown_records"][0]
    assert integrity_record["related_fingerprint"] == fingerprint
    assert integrity_record["related_case_id"] == "case:archive-test"
    assert integrity_record["related_plan_revision_id"] == "plan:archive-test:v1"

    atom_actions = {atom_id: {"atom_id": atom_id, "status": "new"}}
    result = sync_atom_actions_from_plan_folders(
        atom_actions=atom_actions,
        owner_roots=[owner_root],
        generated_at="2026-07-10T00:00:00Z",
    )
    assert result["integrity_unknown_ticket_files"] == 1
    assert atom_actions[atom_id]["status"] == "new"
    assert "last_plan_seen_at" not in atom_actions[atom_id]


def test_integrity_archive_is_idempotent_for_already_archived_copy(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "3030303030303030"
    archived = (
        owner_root / ".agents" / "plans" / "6 - archived" / f"20260210_{fingerprint}_corrupt.md"
    )
    archived.parent.mkdir(parents=True)
    payload = b"from mypy import build\n"
    archived.write_bytes(payload)
    payload_sha256 = hashlib.sha256(payload).hexdigest()

    first = archive_integrity_unknown_plan_ticket_file(
        owner_root=owner_root,
        path=archived,
        reason="Unrelated Python source",
        expected_source_sha256=payload_sha256,
    )
    sidecar = first.with_suffix(f"{first.suffix}.outcome.json")
    first_sidecar_bytes = sidecar.read_bytes()

    second = archive_integrity_unknown_plan_ticket_file(
        owner_root=owner_root,
        path=first,
        reason="Unrelated Python source",
        expected_source_sha256=payload_sha256,
    )

    assert first == archived
    assert second == archived
    assert archived.read_bytes() == payload
    assert sidecar.read_bytes() == first_sidecar_bytes


def test_integrity_archive_rejects_sha_mismatch_before_mutation(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "4040404040404040"
    source = (
        owner_root / ".agents" / "plans" / "5 - complete" / f"20260210_{fingerprint}_corrupt.md"
    )
    source.parent.mkdir(parents=True)
    source.write_bytes(b"untrusted bytes")

    with pytest.raises(ValueError, match="integrity_archive_source_sha256_mismatch"):
        archive_integrity_unknown_plan_ticket_file(
            owner_root=owner_root,
            path=source,
            reason="Unrelated content",
            expected_source_sha256="0" * 64,
        )

    assert source.read_bytes() == b"untrusted bytes"
    assert not (owner_root / ".agents" / "plans" / "6 - archived").exists()


def test_integrity_archive_rejects_path_outside_plan_root(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "5050505050505050"
    outside = tmp_path / f"20260210_{fingerprint}_outside.md"
    outside.write_bytes(b"outside")

    with pytest.raises(ValueError, match="outside plan root"):
        archive_integrity_unknown_plan_ticket_file(
            owner_root=owner_root,
            path=outside,
            reason="Unrelated content",
            expected_source_sha256=hashlib.sha256(b"outside").hexdigest(),
        )

    assert outside.read_bytes() == b"outside"
    assert not (owner_root / ".agents").exists()


@pytest.mark.parametrize("legacy", [False, True], ids=["current", "legacy"])
def test_normal_archive_keeps_valid_plan_on_markdown_outcome_path(
    tmp_path: Path,
    legacy: bool,
) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "6060606060606060"
    source = (
        owner_root
        / ".agents"
        / "plans"
        / "5 - complete"
        / f"20260211_{fingerprint}_{'legacy' if legacy else 'current'}.md"
    )
    if legacy:
        source.parent.mkdir(parents=True)
        source.write_text(
            f"# Valid legacy plan\n\n- Fingerprint: `{fingerprint}`\n",
            encoding="utf-8",
        )
    else:
        _write_plan(source, fingerprint, "Valid current plan")
    before = source.read_bytes()

    archived = archive_plan_ticket_file(
        owner_root=owner_root,
        path=source,
        disposition="duplicate",
        related_fingerprint=fingerprint,
        reason="Duplicate valid plan",
    )

    assert archived.read_bytes() != before
    assert not archived.with_suffix(f"{archived.suffix}.outcome.json").exists()
    outcome = extract_outcome_markdown(archived.read_text(encoding="utf-8"))
    assert outcome is not None
    assert outcome["state"] == "duplicate"


def test_archive_preserves_undecodable_historical_bytes(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "fedcba9876543210"
    source = owner_root / ".agents" / "plans" / "2 - ready" / f"20260709_{fingerprint}_corrupt.md"
    source.parent.mkdir(parents=True)
    original = b"# corrupt\n\xff\xfe historical"
    source.write_bytes(original)

    from backlog_repo.plan_index import archive_plan_ticket_file

    archived = archive_plan_ticket_file(
        owner_root=owner_root,
        path=source,
        disposition="superseded",
        related_fingerprint="0123456789abcdef",
        reason="Historical replacement",
    )

    assert archived.read_bytes() == original
    sidecar = archived.with_suffix(f"{archived.suffix}.outcome.json")
    outcome = json.loads(sidecar.read_text(encoding="utf-8"))
    assert outcome["state"] == "integrity_unknown"
    assert outcome["integrity_reason"] == "plan_copy_invalid_utf8"
    assert outcome["archive_reason"] == "Historical replacement"
    assert outcome["intended_disposition"] == "unverified"
    assert outcome["related_fingerprint"] == "0123456789abcdef"
    index = scan_plan_ticket_index(owner_root=owner_root)
    assert index[fingerprint]["status"] == "integrity_unknown"
    assert index[fingerprint]["paths"] == []
    assert index[fingerprint]["integrity_unknown_paths"] == [str(archived)]
    assert index[fingerprint]["integrity_unknown_reasons"] == ["plan_copy_invalid_utf8"]
    assert "case_ids" not in index[fingerprint]


def test_archive_marks_utf8_nul_corruption_integrity_unknown(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "0badc0de0badc0de"
    source = (
        owner_root / ".agents" / "plans" / "2 - ready" / f"20260709_{fingerprint}_nul-corrupt.md"
    )
    source.parent.mkdir(parents=True)
    original = b"# valid utf8 prefix\n\x00{unrelated batch json}\n"
    source.write_bytes(original)

    from backlog_repo.plan_index import archive_plan_ticket_file

    archived = archive_plan_ticket_file(
        owner_root=owner_root,
        path=source,
        disposition="superseded",
        related_fingerprint="0123456789abcdef",
        reason="Historical replacement",
    )

    assert archived.read_bytes() == original
    sidecar = archived.with_suffix(f"{archived.suffix}.outcome.json")
    outcome = json.loads(sidecar.read_text(encoding="utf-8"))
    assert outcome["state"] == "integrity_unknown"
    assert outcome["integrity_reason"] == "plan_copy_contains_nul_byte"
    assert outcome["archive_reason"] == "Historical replacement"
    assert outcome["intended_disposition"] == "unverified"
    index = scan_plan_ticket_index(owner_root=owner_root)
    assert index[fingerprint]["status"] == "integrity_unknown"
    assert index[fingerprint]["paths"] == []
    assert index[fingerprint]["buckets"] == []
    assert index[fingerprint]["integrity_unknown_paths"] == [str(archived)]
    assert index[fingerprint]["integrity_unknown_buckets"] == ["6 - archived"]
    assert index[fingerprint]["integrity_unknown_reasons"] == ["plan_copy_contains_nul_byte"]
    assert index[fingerprint]["integrity_unknown_records"] == [
        {
            "path": str(archived),
            "bucket": "6 - archived",
            "state": "integrity_unknown",
            "outcome_scope": "plan_copy",
            "reason": "plan_copy_contains_nul_byte",
            "canonical": False,
            "sidecar_state": "integrity_unknown",
            "related_fingerprint": "0123456789abcdef",
        }
    ]
    assert "case_ids" not in index[fingerprint]
    assert "plan_revision_ids" not in index[fingerprint]
    assert "outcome_states" not in index[fingerprint]
    assert "relationship_outcome_states" not in index[fingerprint]


def test_integrity_unknown_archive_cannot_displace_readable_complete_plan(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "fedcba9876543210"
    name = f"20260709_{fingerprint}_case.md"
    complete = owner_root / ".agents" / "plans" / "5 - complete" / name
    corrupt = owner_root / ".agents" / "plans" / "2 - ready" / name
    _write_plan(complete, fingerprint, "Readable completed plan")
    corrupt.parent.mkdir(parents=True)
    corrupt.write_bytes(b"# corrupt\n\xff\xfe\x00historical")

    from backlog_repo.plan_index import archive_plan_ticket_file

    archived = archive_plan_ticket_file(
        owner_root=owner_root,
        path=corrupt,
        disposition="superseded",
        related_fingerprint=fingerprint,
        reason="Historical replacement",
    )

    assert dedupe_actioned_plan_ticket_files(owner_root=owner_root) == 0
    assert complete.exists()
    index = scan_plan_ticket_index(owner_root=owner_root)
    assert index[fingerprint]["paths"] == [str(complete)]
    assert index[fingerprint]["status"] == "actioned"
    assert str(archived) in index[fingerprint]["integrity_unknown_paths"]
    assert "plan_copy_contains_nul_byte" in index[fingerprint]["integrity_unknown_reasons"]
    assert "relationship_outcome_states" not in index[fingerprint]


def test_active_nul_corrupt_plan_cannot_promote_atom_lifecycle(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "0123456789abcdef"
    atom_id = "usertest/20260709T000000Z/codex/0:suggested_change:3"
    corrupt = (
        owner_root / ".agents" / "plans" / "2 - ready" / f"20260709_{fingerprint}_nul-corrupt.md"
    )
    corrupt.parent.mkdir(parents=True)
    corrupt.write_bytes(f"Evidence: `{atom_id}`\n".encode() + b"\x00corrupt")
    atom_actions = {
        atom_id: {
            "atom_id": atom_id,
            "status": "new",
            "fingerprints": [fingerprint],
        }
    }

    result = sync_atom_actions_from_plan_folders(
        atom_actions=atom_actions,
        owner_roots=[owner_root],
        generated_at="2026-07-10T00:00:00Z",
    )

    assert result["integrity_unknown_ticket_files"] == 1
    assert atom_actions[atom_id]["status"] == "new"
    assert "last_plan_seen_at" not in atom_actions[atom_id]


def test_nul_corrupt_plan_cannot_keep_stale_atom_queued(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "fedcba9876543210"
    atom_id = "usertest/20260709T000000Z/codex/0:suggested_change:4"
    corrupt = (
        owner_root / ".agents" / "plans" / "2 - ready" / f"20260709_{fingerprint}_nul-corrupt.md"
    )
    corrupt.parent.mkdir(parents=True)
    corrupt.write_bytes(b"# queued\x00corrupt")
    atom_actions = {
        atom_id: {
            "atom_id": atom_id,
            "status": "queued",
            "fingerprints": [fingerprint],
            "queue_paths": [str(corrupt)],
        }
    }

    result = reconcile_missing_plan_atoms(
        atom_actions=atom_actions,
        owner_roots=[owner_root],
        generated_at="2026-07-10T00:00:00Z",
    )

    assert result["live_fingerprints"] == 0
    assert result["atoms_with_existing_queue_path"] == 0
    assert result["atoms_demoted"] == 1
    assert atom_actions[atom_id]["status"] == "new"


def test_scan_rejects_conflicting_active_outcome_states(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "0123456789abcdef"
    base = {
        "schema_version": 1,
        "case_id": "case:conflict",
        "plan_revision_id": "plan:conflict:v1",
        "recorded_at": "2026-07-09T00:00:00Z",
        "requires_live_verification": False,
        "target_branch": "dev",
        "merged_commit": "abc123",
        "test_evidence": [
            _passed(
                "test",
                "tests/test_x.py",
                case_id="case:conflict",
                plan_revision_id="plan:conflict:v1",
                fingerprint=fingerprint,
            )
        ],
        "original_scenario_evidence": [],
        "live_evidence": [],
        "remaining_risks": [],
        "recurrence_check": {"status": "not_run"},
    }
    for bucket, state in (("3 - in_progress", "tests_verified"), ("5 - complete", "resolved")):
        path = owner_root / ".agents" / "plans" / bucket / f"20260709_{fingerprint}_{state}.md"
        _write_plan(path, fingerprint, state)
        record = {**base, "state": state}
        if state == "resolved":
            record["original_scenario_evidence"] = [
                _passed(
                    "original_scenario",
                    "runs/replay",
                    case_id="case:conflict",
                    plan_revision_id="plan:conflict:v1",
                    fingerprint=fingerprint,
                )
            ]
            record["recurrence_check"] = {
                "status": "completed",
                "result": "passed",
                "evidence": [
                    _passed(
                        "recurrence",
                        "runs/recurrence",
                        case_id="case:conflict",
                        plan_revision_id="plan:conflict:v1",
                        fingerprint=fingerprint,
                    )
                ],
            }
        path.write_text(
            upsert_outcome_markdown(path.read_text(encoding="utf-8"), record),
            encoding="utf-8",
        )

    with pytest.raises(ValueError, match="conflicting_active_outcomes"):
        scan_plan_ticket_index(owner_root=owner_root)


def test_plan_sync_projects_full_case_outcome_record(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "0123456789abcdef"
    atom_id = "usertest/20260709T000000Z/codex/0:suggested_change:1"
    plan_revision_id = "plan:archive-test:v1"
    path = owner_root / ".agents" / "plans" / "5 - complete" / f"20260709_{fingerprint}_done.md"
    _write_plan(path, fingerprint, "Completed")
    markdown = path.read_text(encoding="utf-8").replace(
        "- Plan revision ID: `plan:archive-test:v1`",
        f"- Plan revision ID: `{plan_revision_id}`",
    )
    markdown += f"\n## Evidence atom ids\n\n- `{atom_id}`\n"
    outcome = {
        "schema_version": 1,
        "case_id": "case:archive-test",
        "plan_revision_id": plan_revision_id,
        "state": "tests_verified",
        "outcome_scope": "case",
        "recorded_at": "2026-07-09T00:00:00Z",
        "requires_live_verification": False,
        "target_branch": "dev",
        "merged_commit": "abc123",
        "test_evidence": [
            _passed(
                "test",
                "tests/test_x.py",
                case_id="case:archive-test",
                plan_revision_id=plan_revision_id,
                fingerprint=fingerprint,
            )
        ],
        "original_scenario_evidence": [],
        "live_evidence": [],
        "remaining_risks": ["Original replay pending"],
        "recurrence_check": {"status": "not_run"},
    }
    path.write_text(upsert_outcome_markdown(markdown, outcome), encoding="utf-8")
    atom_actions: dict[str, dict[str, object]] = {}

    sync_atom_actions_from_plan_folders(
        atom_actions=atom_actions,
        owner_roots=[owner_root],
        generated_at="2026-07-10T00:00:00Z",
    )

    projection = atom_actions[atom_id]["plan_outcomes"][plan_revision_id]
    assert projection["required"] is True
    assert projection["outcome_record"]["state"] == "tests_verified"
    assert atom_actions[atom_id]["last_outcome_record"]["outcome_scope"] == "case"


def test_plan_copy_archive_does_not_project_case_outcome(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    fingerprint = "fedcba9876543210"
    atom_id = "usertest/20260709T000000Z/codex/0:suggested_change:2"
    source = owner_root / ".agents" / "plans" / "2 - ready" / f"20260709_{fingerprint}_copy.md"
    _write_plan(source, fingerprint, "Copy")
    source.write_text(
        source.read_text(encoding="utf-8") + f"\n## Evidence atom ids\n\n- `{atom_id}`\n",
        encoding="utf-8",
    )

    from backlog_repo.plan_index import archive_plan_ticket_file

    archive_plan_ticket_file(
        owner_root=owner_root,
        path=source,
        disposition="duplicate",
        related_fingerprint=fingerprint,
        reason="Duplicate copy",
    )
    atom_actions: dict[str, dict[str, object]] = {}
    sync_atom_actions_from_plan_folders(
        atom_actions=atom_actions,
        owner_roots=[owner_root],
        generated_at="2026-07-10T00:00:00Z",
    )

    entry = atom_actions[atom_id]
    assert "last_outcome_state" not in entry
    assert "last_outcome_record" not in entry
    assert "plan_outcomes" not in entry
    assert entry["last_plan_copy_disposition"] == "duplicate"
