from __future__ import annotations

import pytest

from backlog_repo import (
    canonical_plan_sha256,
    canonical_ticket_body,
    canonical_ticket_body_sha256,
    is_generated_backlog_ticket,
    parse_verification_contract_markdown,
    render_verification_contract_markdown,
    verification_commands_sha256,
)


def test_generated_origin_recognizes_current_and_legacy_exporters() -> None:
    assert is_generated_backlog_ticket(
        "Generated by `python -m usertest_backlog.cli reports export-tickets` on now."
    )
    assert is_generated_backlog_ticket(
        "Generated by `python -m usertest.cli reports export-tickets` on 2026-02-11."
    )
    assert not is_generated_backlog_ticket(
        "Generated from tracked idea plan `.agents/plans/0 - roadmaps/IDEA-005.md`."
    )


def test_verification_contract_round_trips_exact_commands() -> None:
    commands = ["pytest tests/test_depth.py -q", "ruff check src tests"]
    markdown = render_verification_contract_markdown(commands)

    parsed = parse_verification_contract_markdown(markdown)

    assert parsed == {
        "schema_version": 1,
        "commands": commands,
        "contract_sha256": verification_commands_sha256(commands),
    }


def test_verification_contract_rejects_duplicate_commands() -> None:
    with pytest.raises(ValueError, match="commands_duplicate"):
        render_verification_contract_markdown(["pytest -q", "pytest -q"])


def test_verification_contract_rejects_forged_hash() -> None:
    markdown = render_verification_contract_markdown(["pytest -q"])
    forged = markdown.replace(
        verification_commands_sha256(["pytest -q"]),
        "f" * 64,
    )

    with pytest.raises(ValueError, match="hash_mismatch"):
        parse_verification_contract_markdown(forged)


def test_generated_plan_projects_to_exported_body() -> None:
    body = (
        "- Fingerprint: `0123456789abcdef`\n"
        "- Case ID: `case:test`\n"
        "- Plan revision ID: `plan:test:v1`\n\n"
        "## Implementation plan\n\n"
        + render_verification_contract_markdown(["pytest -q"])
        + "\n"
    )
    local_plan = (
        "# Ticket\n\n"
        "Generated by `python -m usertest_backlog.cli reports export-tickets` on now.\n"
        "- Fingerprint: `0123456789abcdef`\n"
        "- Case ID: `case:test`\n"
        "- Plan revision ID: `plan:test:v1`\n\n"
        f"{body}"
    )

    assert canonical_ticket_body(local_plan) == canonical_ticket_body(body)
    assert canonical_ticket_body_sha256(local_plan) == canonical_ticket_body_sha256(body)


def test_outcome_append_does_not_change_canonical_plan_hash() -> None:
    plan = "# Ticket\n- Fingerprint: `0123456789abcdef`\n"
    with_outcome = (
        plan
        + "\n<!-- backlog-outcome:start -->\n"
        + '{"schema_version":1,"state":"implemented"}\n'
        + "<!-- backlog-outcome:end -->\n"
    )

    assert canonical_plan_sha256(with_outcome) == canonical_plan_sha256(plan)


def test_generated_plan_rejects_ambiguous_wrapper_marker() -> None:
    marker = "Generated by `python -m usertest_backlog.cli reports export-tickets`"
    markdown = f"# Ticket\n\n{marker}\n- Fingerprint: `a`\n\nbody\n{marker}\n"

    with pytest.raises(ValueError, match="marker_ambiguous"):
        canonical_ticket_body(markdown)
