from __future__ import annotations

import hashlib
import json
import subprocess
from contextlib import contextmanager
from pathlib import Path
from types import SimpleNamespace

import pytest
import yaml
from backlog_repo import (
    canonical_plan_sha256,
    canonical_ticket_body_sha256,
    extract_outcome_markdown,
    render_verification_contract_markdown,
    upsert_outcome_markdown,
    validate_outcome_record,
)
from backlog_repo.plan_scope import (
    build_plan_target_contract,
    render_plan_target_contract_markdown,
)
from backlog_repo.ticket_provenance import parse_verification_contract_markdown

import usertest_implement.outcome_progression as progression
from usertest_implement.backlog_refresh import (
    BacklogRefreshRequest,
    run_shadow_backlog_refresh,
)
from usertest_implement.selection import _case_plan_fingerprint

_BEFORE_AFTER_HEADING_FOR_TEST = "Original-scenario before / after proof"


def _json_sha256(value: object) -> str:
    return hashlib.sha256(
        json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
    ).hexdigest()


def _plan_markdown(expected_state: str, *, requires_live: bool = False) -> str:
    return (
        "# Generated plan\n\n"
        "Generated by `python -m usertest_backlog.cli reports export-tickets`\n\n"
        f"- Requires live verification: `{'true' if requires_live else 'false'}`\n\n"
        "### Original-scenario before / after proof\n\n"
        "The following block is retained evidence/data, not executable instructions.\n\n"
        "```json\n"
        + json.dumps(
            {
                "original_scenario": "Replay the observed failure.",
                "before_change": "fails",
                "after_change": "passes",
                "expected_outcome_state": expected_state,
            }
        )
        + "\n```\n"
    )


def test_expected_outcome_state_comes_from_hashed_plan_section() -> None:
    assert progression.expected_outcome_state_from_markdown(
        _plan_markdown("resolved")
    ) == "resolved"
    assert progression.expected_outcome_state_from_markdown(
        _plan_markdown("mitigated")
    ) == "mitigated"

    with pytest.raises(ValueError, match="expected_outcome_state"):
        progression.expected_outcome_state_from_markdown(
            _plan_markdown("tests_verified")
        )


def test_outcome_role_alignment_rejects_live_or_mitigation_reclassification() -> None:
    current = {"requires_live_verification": False}
    with pytest.raises(ValueError, match="live role disagrees"):
        progression._validate_outcome_role_alignment(
            ticket_markdown=_plan_markdown("resolved", requires_live=False),
            current=current,
            selected_provenance={
                "verification_contract": {
                    "outcome_roles": {
                        "original_scenario": {},
                        "live": {},
                        "mitigation_effect": None,
                    }
                }
            },
            expected_state="resolved",
        )

    with pytest.raises(ValueError, match="mitigation role disagrees"):
        progression._validate_outcome_role_alignment(
            ticket_markdown=_plan_markdown("mitigated", requires_live=False),
            current=current,
            selected_provenance={
                "verification_contract": {
                    "outcome_roles": {
                        "original_scenario": {},
                        "live": None,
                        "mitigation_effect": None,
                    }
                }
            },
            expected_state="mitigated",
        )


def _install_progression_fakes(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    *,
    expected_state: str,
    requires_live: bool,
    failing_role: str | None = None,
) -> tuple[dict[str, object], list[str], Path]:
    ticket_path = tmp_path / ".agents" / "plans" / "5 - complete" / "plan.md"
    selected = SimpleNamespace(
        fingerprint="0123456789abcdef",
        ticket_markdown=_plan_markdown(
            expected_state,
            requires_live=requires_live,
        ),
    )
    state: dict[str, object] = {
        "state": "tests_verified",
        "case_id": "case:one",
        "plan_revision_id": "plan:one:v1",
        "merged_commit": "a" * 40,
        "requires_live_verification": requires_live,
        "test_evidence": [{"result": "passed"}],
        "original_scenario_evidence": [],
        "live_evidence": [],
        "mitigation_evidence": [],
        "remaining_risks": [
            "Original failure scenario has not been replayed after merge",
            *(["Live runtime verification is still required"] if requires_live else []),
        ],
        "recurrence_check": {"status": "not_run"},
    }
    roles: list[str] = []

    monkeypatch.setattr(
        progression,
        "_select_review_ticket",
        lambda **_: selected,
    )
    monkeypatch.setattr(progression, "is_generated_backlog_ticket", lambda _: True)
    monkeypatch.setattr(
        progression,
        "_selected_ticket_provenance",
        lambda *_args, **_kwargs: {
            "verification_contract": {
                "outcome_roles": {
                    "original_scenario": {"role_contract_sha256": "d" * 64},
                    "live": (
                        {"role_contract_sha256": "e" * 64}
                        if requires_live
                        else None
                    ),
                    "mitigation_effect": (
                        {"role_contract_sha256": "f" * 64}
                        if expected_state == "mitigated"
                        else None
                    ),
                }
            },
            "verification_contract_sha256": "b" * 64,
            "target_contract_sha256": "c" * 64,
        },
    )
    monkeypatch.setattr(progression, "_load_current", lambda _path: dict(state))
    current_state = state

    def _fake_transition(*, state: str, updates: dict[str, object], **_kwargs):
        current_state.update(updates)
        current_state["state"] = state
        return dict(current_state)

    monkeypatch.setattr(progression, "_transition", _fake_transition)

    @contextmanager
    def _fake_worktree(**_kwargs):
        yield tmp_path

    monkeypatch.setattr(progression, "clean_merged_commit_worktree", _fake_worktree)

    def _fake_run_role(*, role: str, output_path: Path, **_kwargs):
        roles.append(role)
        if role == failing_role:
            raise progression.OutcomeRoleDidNotPass(
                role=role,
                artifact_path=output_path,
                timed_out=False,
            )
        return {
            "kind": "runner_outcome_role",
            "reference": str(output_path),
            "result": "passed",
        }

    monkeypatch.setattr(progression, "_run_role", _fake_run_role)
    return state, roles, ticket_path


@pytest.mark.parametrize(
    ("expected_state", "requires_live", "expected_roles"),
    [
        ("resolved", False, ["original_scenario"]),
        ("resolved", True, ["original_scenario", "live"]),
        (
            "mitigated",
            True,
            ["original_scenario", "live", "mitigation_effect"],
        ),
    ],
)
def test_progression_runs_only_causally_required_roles(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    expected_state: str,
    requires_live: bool,
    expected_roles: list[str],
) -> None:
    state, roles, ticket_path = _install_progression_fakes(
        monkeypatch,
        tmp_path,
        expected_state=expected_state,
        requires_live=requires_live,
    )

    result = progression.progress_post_merge_outcome(
        repo_root=tmp_path,
        owner_root=tmp_path,
        ticket_path=ticket_path,
        ledger_path=tmp_path / "ledger.yaml",
    )

    assert result.complete is True
    assert result.final_state == expected_state
    assert roles == expected_roles
    if expected_state == "resolved":
        assert state["recurrence_check"] == {
            "status": "not_observed",
            "result": "no_new_source_window",
            "evidence": [],
        }
        assert any("Recurrence has not yet" in risk for risk in state["remaining_risks"])
    else:
        assert any("not claimed resolved" in risk for risk in state["remaining_risks"])


def test_failed_original_scenario_is_retained_as_unverified_not_success(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    state, roles, ticket_path = _install_progression_fakes(
        monkeypatch,
        tmp_path,
        expected_state="resolved",
        requires_live=False,
        failing_role="original_scenario",
    )

    result = progression.progress_post_merge_outcome(
        repo_root=tmp_path,
        owner_root=tmp_path,
        ticket_path=ticket_path,
        ledger_path=tmp_path / "ledger.yaml",
    )

    assert result.complete is False
    assert result.final_state == "unverified"
    assert state["state"] == "unverified"
    assert roles == ["original_scenario"]
    assert "did not satisfy its causal predicates" in str(result.detail)


def test_structural_terminal_state_is_not_reported_complete_without_provenance(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    state, roles, ticket_path = _install_progression_fakes(
        monkeypatch,
        tmp_path,
        expected_state="resolved",
        requires_live=False,
    )
    state["state"] = "resolved"
    state["original_scenario_evidence"] = [
        {"kind": "runner_outcome_role", "reference": "forged", "result": "passed"}
    ]
    monkeypatch.setattr(
        progression,
        "_require_terminal_outcome_provenance",
        lambda **_: (_ for _ in ()).throw(ValueError("retained artifact hash mismatch")),
    )

    result = progression.progress_post_merge_outcome(
        repo_root=tmp_path,
        owner_root=tmp_path,
        ticket_path=ticket_path,
        ledger_path=tmp_path / "ledger.yaml",
    )

    assert result.complete is False
    assert result.status == "blocked"
    assert result.final_state == "resolved"
    assert roles == []
    assert "artifact hash mismatch" in str(result.detail)


def test_unverified_retry_reuses_passed_original_and_runs_only_missing_live_role(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    state, roles, ticket_path = _install_progression_fakes(
        monkeypatch,
        tmp_path,
        expected_state="resolved",
        requires_live=True,
    )
    state["state"] = "unverified"
    state["original_scenario_evidence"] = [
        {"kind": "runner_outcome_role", "reference": "prior", "result": "passed"}
    ]
    monkeypatch.setattr(
        progression,
        "_has_bound_passing_role_evidence",
        lambda *, current, field, **_kwargs: bool(current.get(field)),
    )

    result = progression.progress_post_merge_outcome(
        repo_root=tmp_path,
        owner_root=tmp_path,
        ticket_path=ticket_path,
        ledger_path=tmp_path / "ledger.yaml",
    )

    assert result.complete is True
    assert roles == ["live"]
    assert state["state"] == "resolved"


def test_reused_role_evidence_must_reopen_and_revalidate_exact_artifact(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    artifact_path = tmp_path / "runs" / "outcome_role.json"
    receipt = {
        "role_artifact_path": str(artifact_path),
        "role_artifact_sha256": "a" * 64,
        "evidence_kind": "original_scenario",
    }
    current = {
        "case_id": "case:one",
        "plan_revision_id": "plan:one:v1",
        "merged_commit": "b" * 40,
        "ticket_provenance": {"verified_implementation_head": "b" * 40},
        "original_scenario_evidence": [
            {
                "kind": "runner_outcome_role",
                "reference": str(artifact_path),
                "result": "passed",
                "runner_receipt": receipt,
            }
        ],
    }
    selected_provenance = {
        "verification_contract": {"outcome_roles": {"original_scenario": {}}},
        "verification_contract_sha256": "c" * 64,
        "target_contract_sha256": "d" * 64,
    }
    monkeypatch.setattr(
        progression,
        "validate_bound_outcome_role_receipt",
        lambda **_: dict(receipt),
    )
    assert progression._has_bound_passing_role_evidence(
        current=current,
        field="original_scenario_evidence",
        role="original_scenario",
        selected_provenance=selected_provenance,
        trusted_runs_root=tmp_path / "runs",
    )

    monkeypatch.setattr(
        progression,
        "validate_bound_outcome_role_receipt",
        lambda **_: {**receipt, "role_artifact_sha256": "e" * 64},
    )
    assert not progression._has_bound_passing_role_evidence(
        current=current,
        field="original_scenario_evidence",
        role="original_scenario",
        selected_provenance=selected_provenance,
        trusted_runs_root=tmp_path / "runs",
    )


def test_role_runner_receives_no_default_timeout(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    observed: dict[str, object] = {}

    def _fake_runner(**kwargs):
        observed.update(kwargs)
        return {"passed": True, "timed_out": False}

    monkeypatch.setattr(
        progression,
        "validate_bound_outcome_role_receipt",
        lambda **_: {"receipt_schema_version": 3},
    )
    evidence = progression._run_role(
        role="original_scenario",
        workspace=tmp_path,
        output_path=tmp_path / "runs" / "outcome_role.json",
        current={
            "case_id": "case:one",
            "plan_revision_id": "plan:one:v1",
            "merged_commit": "a" * 40,
            "ticket_provenance": {"verified_implementation_head": "a" * 40},
        },
        selected_provenance={
            "verification_contract": {
                "outcome_roles": {
                    "original_scenario": {"role_contract_sha256": "d" * 64}
                }
            },
            "verification_contract_sha256": "b" * 64,
            "target_contract_sha256": "c" * 64,
        },
        trusted_runs_root=tmp_path / "runs",
        role_runner=_fake_runner,
    )

    assert observed["timeout_seconds"] is None
    assert evidence["result"] == "passed"


def test_clean_worktree_uses_exact_merged_commit_and_removes_it(tmp_path: Path) -> None:
    repository = tmp_path / "repo"
    repository.mkdir()
    subprocess.run(["git", "init"], cwd=repository, check=True, capture_output=True)
    subprocess.run(
        ["git", "config", "user.email", "tests@example.com"],
        cwd=repository,
        check=True,
    )
    subprocess.run(
        ["git", "config", "user.name", "Tests"], cwd=repository, check=True
    )
    (repository / "probe.txt").write_text("merged behavior\n", encoding="utf-8")
    subprocess.run(["git", "add", "probe.txt"], cwd=repository, check=True)
    subprocess.run(["git", "commit", "-m", "merged"], cwd=repository, check=True)
    commit = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=repository,
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    root = tmp_path / "controlled-worktrees"

    with progression.clean_merged_commit_worktree(
        repository=repository,
        merged_commit=commit,
        worktrees_root=root,
        fingerprint="0123456789abcdef",
    ) as workspace:
        assert subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=workspace,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip() == commit
        # A failed oracle may leave an unexpected path outside its staged overlay.
        # The controlled detached worktree is still destroyed in the context cleanup;
        # no dirty evidence workspace is reused by a later role.
        (workspace / "unexpected-oracle-write.txt").write_text(
            "dirty\n",
            encoding="utf-8",
        )
        created_workspace = workspace

    assert not created_workspace.exists()


def test_refresh_continues_unrelated_work_when_merged_outcome_is_unverified(
    tmp_path: Path,
) -> None:
    owner_root = tmp_path / "owner"
    owner_root.mkdir()
    request = BacklogRefreshRequest(
        repo_root=tmp_path,
        repo_input=str(owner_root),
        runs_dir=tmp_path / "runs",
        target="target",
        backlog_python=tmp_path / "python",
    )
    result = progression.OutcomeProgressionResult(
        fingerprint="0123456789abcdef",
        ticket_path=owner_root / "plan.md",
        starting_state="tests_verified",
        final_state="unverified",
        expected_state="resolved",
        status="blocked",
        detail="original scenario still fails",
    )
    executed: list[str] = []

    class RefreshContinued(RuntimeError):
        pass

    def execute(_argv: list[str], _cwd: Path, label: str) -> None:
        executed.append(label)
        raise RefreshContinued

    with pytest.raises(RefreshContinued):
        run_shadow_backlog_refresh(
            request,
            command_executor=execute,
            open_pr_probe=lambda _request: [],
            outcome_progressor=lambda **_: [result],
        )

    assert executed == ["operational shadow materialization"]


@pytest.mark.parametrize(
    ("implemented_source", "expected_status"),
    [
        ("print('root mechanism fixed')\n", "complete"),
        (
            "try:\n"
            "    raise RuntimeError('root mechanism failed')\n"
            "except RuntimeError:\n"
            "    pass\n",
            "blocked",
        ),
    ],
)
def test_real_post_merge_replay_requires_positive_behavior_for_resolution(
    tmp_path: Path,
    implemented_source: str,
    expected_status: str,
) -> None:
    owner_root = tmp_path / "owner"
    owner_root.mkdir()
    subprocess.run(["git", "init"], cwd=owner_root, check=True, capture_output=True)
    subprocess.run(
        ["git", "config", "user.email", "tests@example.com"],
        cwd=owner_root,
        check=True,
    )
    subprocess.run(
        ["git", "config", "user.name", "Tests"], cwd=owner_root, check=True
    )
    (owner_root / "original_probe.py").write_text(
        "raise RuntimeError('root mechanism failed')\n", encoding="utf-8"
    )
    subprocess.run(["git", "add", "original_probe.py"], cwd=owner_root, check=True)
    subprocess.run(
        ["git", "commit", "-m", "researched failure"], cwd=owner_root, check=True
    )
    researched_commit = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=owner_root,
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    (owner_root / "original_probe.py").write_text(
        implemented_source, encoding="utf-8"
    )
    subprocess.run(["git", "add", "original_probe.py"], cwd=owner_root, check=True)
    subprocess.run(["git", "commit", "-m", "merged fix"], cwd=owner_root, check=True)
    merged_commit = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=owner_root,
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()

    case_id = "case:post-merge"
    plan_revision_id = "plan:post-merge:v1"
    fingerprint = _case_plan_fingerprint(
        case_id=case_id,
        plan_revision_id=plan_revision_id,
    )
    target_contract = build_plan_target_contract(
        {
            "case_id": case_id,
            "problem_id": "problem:post-merge",
            "selected_option_id": "option:root-mechanism",
            "repo_revision": merged_commit,
            "change_targets": [
                {
                    "action": "modify",
                    "path": "original_probe.py",
                    "symbols": ["main"],
                    "change": "Correct the root mechanism observed by the replay.",
                }
            ],
        },
        repo_root=owner_root,
    )
    original_command = "python original_probe.py"
    replay_argv = ["python", "original_probe.py"]
    outcome_oracle = {
        "schema_version": 1,
        "case_id": case_id,
        "repo_revision": researched_commit,
        "research_experiment_id": "experiment:original",
        "scenario_kind": "original_replay",
        "origin_atom_ids": ["atom:post-merge"],
        "mechanism_evidence_ids": ["mechanism_evidence:root-mechanism"],
        "baseline": {
            "exit_code": 1,
            "observable_assertion": {
                "source": "stderr",
                "operator": "contains",
                "expected": "root mechanism failed",
            },
            "stdout_sha256": "a" * 64,
            "stderr_sha256": "b" * 64,
        },
        "kind": "staged_replay",
        "proof_scope": "behavioral",
        "execution": {
            "argv": replay_argv,
            "command_authorization": {
                "authorization_kind": "declared_inspected_repository_entrypoint",
                "executed_argv_sha256": _json_sha256(replay_argv),
                "shell": False,
                "workspace_confined": True,
            },
            "platform_requirement": "any",
            "shell": False,
        },
        "asset": None,
    }
    origin_atom = {
        "atom_id": "atom:post-merge",
        "evidence_role": "observation",
        "origin_stage": "runtime",
        "expected_output": "root mechanism fixed",
    }
    positive_contract = {
        "schema_version": 1,
        "kind": "origin_evidence_semantic_contract",
        "research_experiment_id": "experiment:original",
        "mechanism_evidence_ids": ["mechanism_evidence:root-mechanism"],
        "origin_evidence": {
            "atom_id": "atom:post-merge",
            "atom_sha256": _json_sha256(origin_atom),
            "field_path": "$.expected_output",
            "value_sha256": _json_sha256("root mechanism fixed"),
        },
        "postconditions": [
            {"type": "command_exit_code", "command_index": 0, "equals": 0},
            {
                "type": "command_stdout_contains",
                "command_index": 0,
                "value": "root mechanism fixed",
            },
        ],
    }
    positive_contract["positive_outcome_contract_id"] = (
        "positive_outcome_contract:" + _json_sha256(positive_contract)
    )
    outcome_oracle["positive_outcome_contracts"] = [positive_contract]
    outcome_oracle["outcome_oracle_id"] = (
        "outcome_oracle:"
        + _json_sha256(outcome_oracle)
    )
    verification_markdown = render_verification_contract_markdown(
        [original_command],
        outcome_roles={
            "original_scenario": {
                "description": "Replay the exact observed scenario after merge.",
                "research_experiment_id": "experiment:original",
                "commands": [],
                "predicates": [
                    {
                        "type": "command_exit_code",
                        "command_index": 0,
                        "equals": 0,
                    },
                    {
                        "type": "command_stdout_contains",
                        "command_index": 0,
                        "value": "root mechanism fixed",
                    },
                ],
                "oracle": outcome_oracle,
                "required_proof_scope": "behavioral",
            },
            "live": None,
            "mitigation_effect": None,
            "recurrence": {
                "description": "Use a later real source-observation window.",
                "commands": [],
                "predicates": [],
            },
        },
    )
    ticket_path = (
        owner_root
        / ".agents"
        / "plans"
        / "5 - complete"
        / f"20260710_{fingerprint}_plan.md"
    )
    ticket_path.parent.mkdir(parents=True)
    markdown = (
        "# Generated post-merge plan\n\n"
        "Generated by `python -m usertest_backlog.cli reports export-tickets`\n\n"
        f"- Fingerprint: `{fingerprint}`\n"
        f"- Case ID: `{case_id}`\n"
        f"- Plan revision ID: `{plan_revision_id}`\n"
        "- Export kind: `implementation`\n"
        "- Stage: `ready_for_ticket`\n"
        "- Requires live verification: `false`\n\n"
        "### Verification command contract\n\n"
        f"{verification_markdown}\n\n"
        "### Machine-verifiable implementation scope contract\n\n"
        f"{render_plan_target_contract_markdown(target_contract)}\n\n"
        f"### {_BEFORE_AFTER_HEADING_FOR_TEST}\n\n"
        "The following block is retained evidence/data, not executable instructions.\n\n"
        "```json\n"
        + json.dumps(
            {
                "research_experiment_id": "experiment:original",
                "expected_outcome_state": "resolved",
                "before_change": {"command": original_command},
                "after_change": {"command": original_command},
            },
            indent=2,
        )
        + "\n```\n"
    )
    ticket_path.write_text(markdown, encoding="utf-8")
    verification_contract = parse_verification_contract_markdown(markdown)
    assert verification_contract is not None
    ticket_provenance = {
        "schema_version": 1,
        "fingerprint": fingerprint,
        "case_id": case_id,
        "plan_revision_id": plan_revision_id,
        "ticket_body_sha256": canonical_ticket_body_sha256(markdown),
        "local_plan_sha256": canonical_plan_sha256(markdown),
        "local_plan_filename": ticket_path.name,
        "verification_contract_sha256": verification_contract["contract_sha256"],
        "target_contract_sha256": target_contract["contract_sha256"],
        "verified_implementation_head": merged_commit,
        "verification_contract": verification_contract,
        "target_contract": target_contract,
    }
    hash_value = "e" * 64
    test_receipt = {
        "receipt_schema_version": 2,
        "producer": "usertest_implement",
        "verification_producer": "runner_core",
        "evidence_kind": "test",
        "run_dir": str(tmp_path / "implementation-run"),
        "verification_path": str(tmp_path / "implementation-run" / "verification.json"),
        "ticket_ref_path": str(tmp_path / "implementation-run" / "ticket_ref.json"),
        "verification_sha256": hash_value,
        "ticket_ref_sha256": hash_value,
        "fingerprint": fingerprint,
        "case_id": case_id,
        "plan_revision_id": plan_revision_id,
        "ticket_body_sha256": ticket_provenance["ticket_body_sha256"],
        "local_plan_sha256": ticket_provenance["local_plan_sha256"],
        "local_plan_filename": ticket_path.name,
        "verification_contract_sha256": verification_contract["contract_sha256"],
        "target_contract_sha256": target_contract["contract_sha256"],
        "verification_binding_sha256": hash_value,
        "commands": [original_command],
    }
    outcome = validate_outcome_record(
        {
            "schema_version": 1,
            "case_id": case_id,
            "plan_revision_id": plan_revision_id,
            "state": "tests_verified",
            "recorded_at": "2026-07-10T12:00:00Z",
            "requires_live_verification": False,
            "target_branch": "dev",
            "merged_commit": merged_commit,
            "pr_url": "https://example.invalid/pr/1",
            "test_evidence": [
                {
                    "kind": "runner_verification",
                    "reference": test_receipt["verification_path"],
                    "result": "passed",
                    "runner_receipt": test_receipt,
                }
            ],
            "ci_evidence": [],
            "original_scenario_evidence": [],
            "live_evidence": [],
            "mitigation_evidence": [],
            "remaining_risks": [
                "Original failure scenario has not been replayed after merge"
            ],
            "recurrence_check": {"status": "not_run"},
            "ticket_provenance": ticket_provenance,
        }
    )
    ticket_path.write_text(
        upsert_outcome_markdown(markdown, outcome), encoding="utf-8"
    )
    repo_root = tmp_path / "tool"
    ledger_path = repo_root / ".agents" / "state" / "backlog_implement_actions.yaml"
    ledger_path.parent.mkdir(parents=True)
    ledger_path.write_text(
        yaml.safe_dump(
            {
                "schema_version": 1,
                "updated_at": None,
                "actions": {
                    fingerprint: {
                        "fingerprint": fingerprint,
                        "last_outcome_state": "tests_verified",
                        "outcome": outcome,
                    }
                },
            },
            sort_keys=True,
        ),
        encoding="utf-8",
    )

    if expected_status == "complete":
        premerge_evidence = progression.verify_premerge_original_scenario(
            repo_root=repo_root,
            owner_root=owner_root,
            fingerprint=fingerprint,
            ticket_markdown=markdown,
            current=outcome,
            selected_provenance={
                **ticket_provenance,
                "verification_contract": verification_contract,
            },
        )
        assert premerge_evidence["result"] == "passed"
    else:
        with pytest.raises(
            progression.OutcomeRoleDidNotPass,
            match="did not satisfy its causal predicates",
        ):
            progression.verify_premerge_original_scenario(
                repo_root=repo_root,
                owner_root=owner_root,
                fingerprint=fingerprint,
                ticket_markdown=markdown,
                current=outcome,
                selected_provenance={
                    **ticket_provenance,
                    "verification_contract": verification_contract,
                },
            )

    result = progression.progress_post_merge_outcome(
        repo_root=repo_root,
        owner_root=owner_root,
        ticket_path=ticket_path,
        ledger_path=ledger_path,
    )

    final = extract_outcome_markdown(ticket_path.read_text(encoding="utf-8"))
    assert final is not None
    assert result.status == expected_status
    role_artifacts = list(
        (repo_root / "runs" / "usertest_implement" / "_outcome_roles").rglob(
            "outcome_role.json"
        )
    )
    assert len(role_artifacts) == 1
    premerge_role_artifacts = list(
        (repo_root / "runs" / "usertest_implement" / "_premerge_outcome_roles").rglob(
            "outcome_role.json"
        )
    )
    assert len(premerge_role_artifacts) == 1
    premerge_role_artifact = json.loads(
        premerge_role_artifacts[0].read_text(encoding="utf-8")
    )
    assert premerge_role_artifact["timeout_seconds"] is None
    assert premerge_role_artifact["passed"] is (expected_status == "complete")
    role_artifact = json.loads(role_artifacts[0].read_text(encoding="utf-8"))
    assert role_artifact["timeout_seconds"] is None
    assert role_artifact["commands"][0]["exit_code"] == 0
    assert role_artifact["predicate_results"][0]["passed"] is True
    if expected_status == "complete":
        assert result.complete is True
        assert result.roles_run == ("original_scenario",)
        assert role_artifact["passed"] is True
        assert role_artifact["predicate_results"][1]["passed"] is True
        assert final["state"] == "resolved"
        assert final["original_scenario_evidence"][0]["result"] == "passed"
        assert final["live_evidence"] == []
        assert final["recurrence_check"]["status"] == "not_observed"
        assert final["recurrence_check"]["evidence"] == []
    else:
        assert result.complete is False
        assert result.roles_run == ()
        assert role_artifact["passed"] is False
        assert role_artifact["predicate_results"][1]["passed"] is False
        assert final["state"] == "unverified"
        assert final["original_scenario_evidence"] == []
        assert any(
            "did not satisfy its causal predicates" in risk
            for risk in final["remaining_risks"]
        )
