from __future__ import annotations

import re
from pathlib import Path

import pytest
import yaml
from backlog_repo import (
    canonical_plan_sha256,
    canonical_ticket_body_sha256,
    extract_outcome_markdown,
    transition_outcome_record,
    upsert_outcome_markdown,
)

from usertest_implement.cli import main
from usertest_implement.selection import _case_plan_fingerprint, _select_review_ticket
from usertest_implement.tickets import (
    build_ticket_index,
    move_ticket_file,
    repair_ticket_newline_expansion,
    select_next_ticket_path,
)


def test_repair_ticket_newline_expansion_requires_exact_provenance_match(
    tmp_path: Path,
) -> None:
    original = (
        "# Ticket\n\n"
        "Generated by `python -m usertest_backlog.cli reports export-tickets` now.\n\n"
        "- Fingerprint: `0123456789abcdef`\n\n"
        "Body line one.\nBody line two.\n"
    )
    expanded = re.sub(
        r"\n+",
        lambda match: "\r\r\n" * (len(match.group(0)) * 2),
        original,
    )
    outcome = {
        "schema_version": 1,
        "case_id": "case:newline-repair",
        "plan_revision_id": "plan:newline-repair:v1",
        "state": "planned",
        "recorded_at": "2026-07-19T00:00:00Z",
        "requires_live_verification": False,
        "target_branch": None,
        "merged_commit": None,
        "test_evidence": [],
        "original_scenario_evidence": [],
        "live_evidence": [],
        "mitigation_evidence": [],
        "remaining_risks": [],
        "recurrence_check": {"status": "not_run"},
    }
    expanded = upsert_outcome_markdown(expanded, outcome)
    expected_outcome = extract_outcome_markdown(expanded)
    ticket = tmp_path / "ticket.md"
    ticket.write_bytes(expanded.encode("utf-8"))

    receipt = repair_ticket_newline_expansion(
        path=ticket,
        expected_ticket_body_sha256=canonical_ticket_body_sha256(original),
        expected_local_plan_sha256=canonical_plan_sha256(original),
    )

    assert receipt is not None
    assert receipt["status"] == "repaired"
    repaired = ticket.read_bytes().decode("utf-8")
    assert canonical_ticket_body_sha256(repaired) == canonical_ticket_body_sha256(
        original
    )
    assert canonical_plan_sha256(repaired) == canonical_plan_sha256(original)
    assert extract_outcome_markdown(repaired) == expected_outcome


def test_repair_ticket_newline_expansion_refuses_unproven_content_change(
    tmp_path: Path,
) -> None:
    ticket = tmp_path / "ticket.md"
    ticket.write_text("# Changed ticket\n", encoding="utf-8")
    before = ticket.read_bytes()

    assert (
        repair_ticket_newline_expansion(
            path=ticket,
            expected_ticket_body_sha256="a" * 64,
            expected_local_plan_sha256="b" * 64,
        )
        is None
    )
    assert ticket.read_bytes() == before


def _passed(kind: str, reference: str) -> dict[str, object]:
    if kind == "test":
        receipt = {
            "receipt_schema_version": 2,
            "producer": "usertest_implement",
            "verification_producer": "runner_core",
            "evidence_kind": kind,
            "run_dir": f"runs/{kind}",
            "verification_path": f"runs/{kind}/verification.json",
            "verification_sha256": "a" * 64,
            "ticket_ref_path": f"runs/{kind}/ticket_ref.json",
            "ticket_ref_sha256": "b" * 64,
            "ticket_body_sha256": "c" * 64,
            "local_plan_sha256": "d" * 64,
            "local_plan_filename": "ticket.md",
            "verification_contract_sha256": "e" * 64,
            "verification_binding_sha256": "f" * 64,
            "fingerprint": "0123456789abcdef",
            "case_id": "case:verified-change",
            "plan_revision_id": "plan:verified-change:v1",
            "commands": [f"verify-{kind}"],
        }
    else:
        receipt = {
            "receipt_schema_version": 3,
            "producer": "usertest_implement",
            "verification_producer": "runner_core",
            "evidence_kind": kind,
            "role_artifact_path": f"runs/{kind}/outcome_role.json",
            "role_artifact_sha256": "a" * 64,
            "role_contract_sha256": "b" * 64,
            "ticket_body_sha256": "c" * 64,
            "local_plan_sha256": "d" * 64,
            "local_plan_filename": "ticket.md",
            "verification_contract_sha256": "e" * 64,
            "target_contract_sha256": "f" * 64,
            "verified_implementation_head": "1" * 40,
            "merged_commit": "2" * 40,
            "fingerprint": "0123456789abcdef",
            "case_id": "case:verified-change",
            "plan_revision_id": "plan:verified-change:v1",
        }
    return {
        "kind": kind,
        "reference": reference,
        "result": "passed",
        "runner_receipt": receipt,
    }


def test_ticket_index_and_move(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    ready_dir = owner_root / ".agents" / "plans" / "2 - ready"
    in_progress_dir = owner_root / ".agents" / "plans" / "3 - in_progress"
    ready_dir.mkdir(parents=True)
    in_progress_dir.mkdir(parents=True)

    fingerprint = "deadbeefdeadbeef"
    ticket_path = ready_dir / f"20260220_{fingerprint}_fix-something.md"
    ticket_path.write_text(
        "# Fix something\n\n"
        "- Export kind: `implementation`\n"
        "- Stage: `ready_for_ticket`\n"
        "- Fingerprint: `deadbeefdeadbeef`\n",
        encoding="utf-8",
    )

    index = build_ticket_index(owner_root=owner_root)
    assert fingerprint in index

    selected = select_next_ticket_path(
        index,
        bucket_priority=["2 - ready"],
        kind_priority=["research", "implementation"],
    )
    assert selected is not None
    entry, _ = selected
    assert entry.fingerprint == fingerprint

    dest_dry = move_ticket_file(
        owner_root=owner_root,
        fingerprint=fingerprint,
        to_bucket="3 - in_progress",
        dry_run=True,
    )
    assert dest_dry == in_progress_dir / ticket_path.name
    assert ticket_path.exists()

    dest = move_ticket_file(
        owner_root=owner_root,
        fingerprint=fingerprint,
        to_bucket="3 - in_progress",
        dry_run=False,
    )
    assert dest.exists()
    assert not ticket_path.exists()


def test_ticket_index_repairs_generated_same_bucket_duplicates_first(
    tmp_path: Path,
) -> None:
    owner_root = tmp_path / "repo"
    complete = owner_root / ".agents" / "plans" / "5 - complete"
    complete.mkdir(parents=True)
    fingerprint = "abababababababab"
    marker = "Generated by `python -m usertest_backlog.cli reports export-tickets`."
    older = complete / f"20260708_{fingerprint}_older.md"
    newer = complete / f"20260709_{fingerprint}_newer.md"
    for path, title in ((older, "Older"), (newer, "Newer")):
        path.write_text(
            f"# {title}\n\n{marker}\n\n- Fingerprint: `{fingerprint}`\n",
            encoding="utf-8",
        )

    index = build_ticket_index(owner_root=owner_root)

    assert index[fingerprint].paths == [newer]
    assert not older.exists()
    archived = list((owner_root / ".agents" / "plans" / "6 - archived").glob("*.md"))
    assert len(archived) == 1
    assert "backlog-outcome:start" in archived[0].read_text(encoding="utf-8")


def test_move_ticket_file_creates_recognized_missing_destination_bucket(
    tmp_path: Path,
) -> None:
    owner_root = tmp_path / "repo"
    in_progress = owner_root / ".agents" / "plans" / "3 - in_progress"
    in_progress.mkdir(parents=True)
    fingerprint = "facefacefaceface"
    ticket = in_progress / f"20260719_{fingerprint}_ticket.md"
    ticket.write_text(
        "# Ticket\n\n"
        f"- Fingerprint: `{fingerprint}`\n"
        "- Export kind: `implementation`\n"
        "- Stage: `ready_for_ticket`\n",
        encoding="utf-8",
    )

    destination = move_ticket_file(
        owner_root=owner_root,
        fingerprint=fingerprint,
        to_bucket="4 - for_review",
        dry_run=False,
    )

    assert destination.parent.name == "4 - for_review"
    assert destination.is_file()
    assert not ticket.exists()


def test_move_ticket_file_rejects_unknown_destination_bucket(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="Unknown plan bucket"):
        move_ticket_file(
            owner_root=tmp_path,
            fingerprint="facefacefaceface",
            to_bucket="arbitrary",
            dry_run=False,
        )


def test_review_selector_rejects_filename_metadata_fingerprint_mismatch(
    tmp_path: Path,
) -> None:
    owner_root = tmp_path / "repo"
    bucket = owner_root / ".agents" / "plans" / "4 - for_review"
    bucket.mkdir(parents=True)
    path = bucket / "20260710_aaaaaaaaaaaaaaaa_mismatch.md"
    path.write_text(
        "# Mismatch\n- Fingerprint: `bbbbbbbbbbbbbbbb`\n",
        encoding="utf-8",
    )

    with pytest.raises(ValueError, match="filename and Markdown metadata"):
        _select_review_ticket(
            owner_root=owner_root,
            ticket_path=None,
            fingerprint="aaaaaaaaaaaaaaaa",
        )


def test_review_selector_preserves_case_lifecycle_id_from_markdown(
    tmp_path: Path,
) -> None:
    owner_root = tmp_path / "repo"
    bucket = owner_root / ".agents" / "plans" / "4 - for_review"
    bucket.mkdir(parents=True)
    fingerprint = _case_plan_fingerprint(
        case_id="case:lifecycle",
        plan_revision_id="plan:lifecycle:v1",
    )
    path = bucket / f"20260710_{fingerprint}_lifecycle.md"
    path.write_text(
        "# Lifecycle\n"
        f"- Fingerprint: `{fingerprint}`\n"
        "- Case ID: `case:lifecycle`\n"
        "- Plan revision ID: `plan:lifecycle:v1`\n"
        "- Case lifecycle ID: `case-lifecycle:lifecycle:1`\n",
        encoding="utf-8",
    )

    selected = _select_review_ticket(
        owner_root=owner_root,
        ticket_path=path,
        fingerprint=None,
    )

    assert selected.case_lifecycle_id == "case-lifecycle:lifecycle:1"


def test_move_to_complete_requires_durable_outcome_record(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    for_review_dir = owner_root / ".agents" / "plans" / "4 - for_review"
    complete_dir = owner_root / ".agents" / "plans" / "5 - complete"
    for_review_dir.mkdir(parents=True)
    complete_dir.mkdir(parents=True)
    fingerprint = "0123456789abcdef"
    ticket_path = for_review_dir / f"20260220_{fingerprint}_verified-change.md"
    ticket_path.write_text(
        "# Verified change\n\n"
        f"- Fingerprint: `{fingerprint}`\n"
        "- Case ID: `case:verified-change`\n"
        "- Plan revision ID: `plan:verified-change:v1`\n",
        encoding="utf-8",
    )

    with pytest.raises(ValueError, match="outcome record"):
        move_ticket_file(
            owner_root=owner_root,
            fingerprint=fingerprint,
            to_bucket="5 - complete",
            dry_run=False,
        )

    outcome = {
        "schema_version": 1,
        "case_id": "case:verified-change",
        "plan_revision_id": "plan:verified-change:v1",
        "state": "tests_verified",
        "recorded_at": "2026-07-09T00:00:00Z",
        "requires_live_verification": False,
        "target_branch": "dev",
        "merged_commit": "abc123",
        "test_evidence": [_passed("test", "tests/test_change.py")],
        "original_scenario_evidence": [],
        "live_evidence": [],
        "remaining_risks": ["Original scenario replay pending"],
        "recurrence_check": {"status": "not_run"},
    }
    completed = move_ticket_file(
        owner_root=owner_root,
        fingerprint=fingerprint,
        to_bucket="5 - complete",
        dry_run=False,
        outcome_record=outcome,
    )

    assert completed.parent == complete_dir
    assert '"state": "tests_verified"' in completed.read_text(encoding="utf-8")

    resolved = transition_outcome_record(
        outcome,
        state="resolved",
        recorded_at="2026-07-10T00:00:00Z",
        updates={
            "original_scenario_evidence": [_passed("original_scenario", "runs/replay")],
            "remaining_risks": [],
            "recurrence_check": {
                "status": "completed",
                "result": "passed",
                "evidence": [_passed("recurrence", "runs/recurrence")],
            },
        },
    )
    completed.write_text(
        upsert_outcome_markdown(completed.read_text(encoding="utf-8"), resolved),
        encoding="utf-8",
    )
    move_ticket_file(
        owner_root=owner_root,
        fingerprint=fingerprint,
        to_bucket="5 - complete",
        dry_run=False,
        outcome_record=outcome,
    )
    persisted = extract_outcome_markdown(completed.read_text(encoding="utf-8"))
    assert persisted is not None
    assert persisted["state"] == "resolved"


def test_select_next_ticket_path_prefers_research(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    ready_dir = owner_root / ".agents" / "plans" / "2 - ready"
    ready_dir.mkdir(parents=True)

    impl_fp = "aaaaaaaaaaaaaaaa"
    impl_path = ready_dir / f"20260220_{impl_fp}_implementation.md"
    impl_path.write_text(
        "# Impl\n\n"
        "- Export kind: `implementation`\n"
        "- Stage: `ready_for_ticket`\n"
        "- Fingerprint: `aaaaaaaaaaaaaaaa`\n",
        encoding="utf-8",
    )

    research_fp = "bbbbbbbbbbbbbbbb"
    research_path = ready_dir / f"20260220_{research_fp}_research.md"
    research_path.write_text(
        "# Research\n\n"
        "- Export kind: `research`\n"
        "- Stage: `research_required`\n"
        "- Fingerprint: `bbbbbbbbbbbbbbbb`\n",
        encoding="utf-8",
    )

    index = build_ticket_index(owner_root=owner_root)
    selected = select_next_ticket_path(
        index,
        bucket_priority=["2 - ready"],
        kind_priority=["research", "implementation"],
    )
    assert selected is not None
    _, path = selected
    assert path == research_path


def test_select_next_ticket_path_skips_non_stage6_implementation(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    ready_dir = owner_root / ".agents" / "plans" / "2 - ready"
    ready_dir.mkdir(parents=True)

    triage_fp = "aaaaaaaaaaaaaaaa"
    (ready_dir / f"20260220_{triage_fp}_triage.md").write_text(
        "# Triage\n\n"
        "- Export kind: `implementation`\n"
        "- Stage: `triage`\n"
        "- Fingerprint: `aaaaaaaaaaaaaaaa`\n",
        encoding="utf-8",
    )

    ready_fp = "bbbbbbbbbbbbbbbb"
    ready_path = ready_dir / f"20260220_{ready_fp}_ready.md"
    ready_path.write_text(
        "# Ready\n\n"
        "- Export kind: `implementation`\n"
        "- Stage: `ready_for_ticket`\n"
        "- Fingerprint: `bbbbbbbbbbbbbbbb`\n",
        encoding="utf-8",
    )

    index = build_ticket_index(owner_root=owner_root)
    selected = select_next_ticket_path(
        index,
        bucket_priority=["2 - ready"],
        kind_priority=["implementation"],
    )
    assert selected is not None
    _, path = selected
    assert path == ready_path


def test_move_ticket_file_dedupes_actioned_buckets_and_prevents_downgrade(tmp_path: Path) -> None:
    owner_root = tmp_path / "repo"
    complete_dir = owner_root / ".agents" / "plans" / "5 - complete"
    in_progress_dir = owner_root / ".agents" / "plans" / "3 - in_progress"
    for_review_dir = owner_root / ".agents" / "plans" / "4 - for_review"
    complete_dir.mkdir(parents=True)
    in_progress_dir.mkdir(parents=True)
    for_review_dir.mkdir(parents=True)

    fingerprint = "deadbeefdeadbeef"
    name = f"20260220_{fingerprint}_fix-something.md"
    complete_path = complete_dir / name
    in_progress_path = in_progress_dir / name
    generated_marker = (
        "Generated by `python -m usertest_backlog.cli reports export-tickets`\n\n"
    )
    complete_path.write_text(
        "# Done\n\n" + generated_marker + "- Fingerprint: `deadbeefdeadbeef`\n",
        encoding="utf-8",
    )
    in_progress_path.write_text(
        "# WIP\n\n" + generated_marker + "- Fingerprint: `deadbeefdeadbeef`\n",
        encoding="utf-8",
    )
    assert complete_path.exists()
    assert in_progress_path.exists()

    # Attempting to move "back" from complete -> for_review should no-op to complete.
    dest = move_ticket_file(
        owner_root=owner_root,
        fingerprint=fingerprint,
        to_bucket="4 - for_review",
        dry_run=False,
    )
    assert dest == complete_path
    assert complete_path.exists()
    assert not in_progress_path.exists()


def test_tickets_discard_moves_ticket_and_demotes_atom(tmp_path: Path) -> None:
    repo_root = tmp_path / "repo"
    ready_dir = repo_root / ".agents" / "plans" / "2 - ready"
    ready_dir.mkdir(parents=True)

    fingerprint = "deadbeefdeadbeef"
    atom_id = "usertest/20260220T194226Z/codex/0:suggested_change:2"
    ticket_path = ready_dir / f"20260220_{fingerprint}_bad-solution.md"
    ticket_path.write_text(
        "# Bad solution\n\n"
        f"- Fingerprint: `{fingerprint}`\n\n"
        "## Evidence atom ids\n\n"
        f"- `{atom_id}`\n",
        encoding="utf-8",
    )
    atom_actions_path = repo_root / "configs" / "backlog_atom_actions.yaml"
    atom_actions_path.parent.mkdir(parents=True, exist_ok=True)
    atom_actions_path.write_text(
        yaml.safe_dump(
            {
                "version": 1,
                "atoms": [
                    {
                        "atom_id": atom_id,
                        "status": "queued",
                        "fingerprints": [fingerprint],
                        "queue_paths": [str(ticket_path)],
                    }
                ],
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )

    with pytest.raises(SystemExit) as exc:
        main(
            [
                "--repo-root",
                str(repo_root),
                "tickets",
                "discard",
                "--owner-root",
                str(repo_root),
                "--fingerprint",
                fingerprint,
                "--reason",
                "bad_solution",
                "--note",
                "Generated fix was not acceptable.",
            ]
        )

    assert exc.value.code == 0
    discarded_path = repo_root / ".agents" / "plans" / "0.2 - discarded" / ticket_path.name
    assert discarded_path.exists()
    assert not ticket_path.exists()

    actions_doc = yaml.safe_load((repo_root / "configs" / "backlog_actions.yaml").read_text())
    action = actions_doc["actions"][0]
    assert action["fingerprint"] == fingerprint
    assert action["status"] == "discarded"
    assert action["discard_reason"] == "bad_solution"

    atom_doc = yaml.safe_load(atom_actions_path.read_text(encoding="utf-8"))
    atom = atom_doc["atoms"][0]
    assert atom["status"] == "new"
    assert atom["discarded_fingerprints"] == [fingerprint]
    assert atom["last_discard_reason"] == "bad_solution"
    assert atom["last_discard_note"] == "Generated fix was not acceptable."
