from __future__ import annotations

import json
from hashlib import sha256
from pathlib import Path

import pytest
from backlog_repo import (
    canonical_plan_sha256,
    canonical_ticket_body_sha256,
    parse_verification_contract_markdown,
    render_verification_contract_markdown,
)
from backlog_repo.plan_scope import render_plan_target_contract_markdown

import usertest_implement.commands.run as run_commands
from usertest_implement.cli import build_parser
from usertest_implement.selection import (
    _case_plan_fingerprint,
    _select_ticket_from_export,
    _select_ticket_from_path,
)


def _write_export_fixture(tmp_path: Path) -> tuple[Path, Path, dict[str, object]]:
    owner_root = tmp_path / "repo"
    case_id = "case:selection"
    plan_revision_id = "plan:selection:v1"
    fingerprint = _case_plan_fingerprint(
        case_id=case_id,
        plan_revision_id=plan_revision_id,
    )
    commands = ["pytest tests/test_selection.py -q"]
    target_payload = {
        "schema_version": 2,
        "contract_source": "runner_stage6_target_intent_v2",
        "case_id": case_id,
        "problem_id": "problem:selection",
        "selected_option_id": "option:selection",
        "repo_revision": "a" * 40,
        "targets": [
            {
                "action": "modify",
                "path": "src/core.py",
                "symbols": ["core.run"],
                "change": "Apply the verified intervention.",
                "change_sha256": sha256(b"Apply the verified intervention.").hexdigest(),
                "target_role": "production",
            }
        ],
    }
    target_contract = {
        **target_payload,
        "contract_sha256": sha256(
            json.dumps(
                target_payload,
                sort_keys=True,
                ensure_ascii=False,
                separators=(",", ":"),
            ).encode()
        ).hexdigest(),
    }
    body = (
        f"- Fingerprint: `{fingerprint}`\n"
        f"- Case ID: `{case_id}`\n"
        f"- Plan revision ID: `{plan_revision_id}`\n"
        "- Export kind: `implementation`\n"
        "- Stage: `ready_for_ticket`\n\n"
        "## Implementation plan\n\n"
        "### Verification command contract\n\n"
        f"{render_verification_contract_markdown(commands)}\n"
        "\n### Machine-verifiable implementation scope contract\n\n"
        f"{render_plan_target_contract_markdown(target_contract)}\n"
    )
    plan_path = (
        owner_root
        / ".agents"
        / "plans"
        / "2 - ready"
        / f"20260710_{fingerprint}_ticket.md"
    )
    plan_path.parent.mkdir(parents=True)
    local_markdown = (
        "# Ticket\n\n"
        "Generated by `python -m usertest_backlog.cli reports export-tickets` on now.\n"
        f"- Fingerprint: `{fingerprint}`\n"
        f"- Case ID: `{case_id}`\n"
        f"- Plan revision ID: `{plan_revision_id}`\n\n"
        f"{body}"
    )
    plan_path.write_text(local_markdown, encoding="utf-8")
    contract = parse_verification_contract_markdown(body)
    assert contract is not None
    export = {
        "fingerprint": fingerprint,
        "case_id": case_id,
        "plan_revision_id": plan_revision_id,
        "export_kind": "implementation",
        "title": "Ticket",
        "body_markdown": body,
        "body_sha256": canonical_ticket_body_sha256(body),
        "local_plan_sha256": canonical_plan_sha256(local_markdown),
        "verification_contract_sha256": contract["contract_sha256"],
        "target_contract_sha256": target_contract["contract_sha256"],
        "source_ticket": {
            "fingerprint": fingerprint,
            "case_id": case_id,
            "plan_revision_id": plan_revision_id,
            "stage": "ready_for_ticket",
        },
        "owner_repo": {
            "root": str(owner_root),
            "idea_path": str(plan_path),
        },
    }
    export_path = tmp_path / "tickets_export.json"
    export_path.write_text(
        json.dumps({"schema_version": 1, "exports": [export]}),
        encoding="utf-8",
    )
    return export_path, plan_path, export


def test_selection_binds_outer_export_to_exact_local_plan(tmp_path: Path) -> None:
    export_path, plan_path, export = _write_export_fixture(tmp_path)

    selected = _select_ticket_from_export(
        tickets_export_path=export_path,
        fingerprint=str(export["fingerprint"]),
    )

    assert selected.idea_path == plan_path.resolve()
    assert selected.case_id == export["case_id"]
    assert selected.plan_revision_id == export["plan_revision_id"]
    assert selected.ticket_body_sha256 == export["body_sha256"]
    assert selected.local_plan_sha256 == export["local_plan_sha256"]
    assert selected.target_contract_sha256 == export["target_contract_sha256"]


def test_generated_implementation_starts_from_exact_researched_revision(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    _export_path, plan_path, _export = _write_export_fixture(tmp_path)
    selected = _select_ticket_from_path(plan_path)
    args = build_parser().parse_args(
        [
            "run",
            "--ticket-path",
            str(plan_path),
            "--repo",
            str(selected.owner_root),
            "--no-docker",
            "--dry-run",
            "--no-move-on-start",
            "--no-move-on-commit",
        ]
    )

    assert run_commands._run_selected_ticket(
        args=args,
        repo_root=tmp_path,
        cfg=object(),
        selected=selected,
    ) == 0
    payload = json.loads(capsys.readouterr().out)
    assert payload["run_request"]["ref"] == "a" * 40


def test_selection_rejects_forged_body_even_when_outer_hash_is_recomputed(
    tmp_path: Path,
) -> None:
    export_path, _plan_path, export = _write_export_fixture(tmp_path)
    document = json.loads(export_path.read_text(encoding="utf-8"))
    forged_body = str(export["body_markdown"]).replace(
        "## Implementation plan",
        "## Different implementation plan",
    )
    document["exports"][0]["body_markdown"] = forged_body
    document["exports"][0]["body_sha256"] = canonical_ticket_body_sha256(forged_body)
    export_path.write_text(json.dumps(document), encoding="utf-8")

    with pytest.raises(ValueError, match="does not match the referenced local plan"):
        _select_ticket_from_export(
            tickets_export_path=export_path,
            fingerprint=str(export["fingerprint"]),
        )


def test_selection_rejects_stale_or_cross_plan_export(tmp_path: Path) -> None:
    export_path, plan_path, export = _write_export_fixture(tmp_path)
    plan_path.write_text(
        plan_path.read_text(encoding="utf-8") + "\nUnreviewed local mutation.\n",
        encoding="utf-8",
    )

    with pytest.raises(ValueError, match="does not match the referenced local plan"):
        _select_ticket_from_export(
            tickets_export_path=export_path,
            fingerprint=str(export["fingerprint"]),
        )
