from __future__ import annotations

import json
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest
import yaml
from backlog_repo import render_verification_contract_markdown
from backlog_repo.plan_scope import (
    build_plan_target_contract,
    render_plan_target_contract_markdown,
)

import usertest_implement.commands.handoff as handoff_commands
from usertest_implement.implementation_provenance import record_verified_implementation_head
from usertest_implement.outcome_evidence import (
    build_verification_binding,
    validate_bound_runner_verification,
)
from usertest_implement.selection import (
    _case_plan_fingerprint,
    _select_ticket_from_path,
    _selected_ticket_provenance,
)

PLAN_COMMANDS = [
    "python -m pytest -q tests/test_original.py",
    "python -m pytest -q tests/test_focused.py",
]
EXTRA_COMMANDS = [
    "python -m pytest -q tests/test_extra_1.py",
    "python -m pytest -q tests/test_extra_2.py",
    "python -m pytest -q tests/test_extra_3.py",
    "python -m pytest -q tests/test_extra_4.py",
]
PR_URL = "https://github.com/example/project/pull/213"


def _git(repo: Path, *args: str) -> str:
    proc = subprocess.run(
        ["git", *args],
        cwd=repo,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return proc.stdout.strip()


def _write_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")


@dataclass(frozen=True)
class AdoptionFixture:
    controller_root: Path
    owner_root: Path
    ticket_path: Path
    workspace: Path
    source_run_dir: Path
    runs_root: Path
    ledger_path: Path
    fingerprint: str
    case_id: str
    plan_revision_id: str
    branch: str
    planned_revision: str
    head: str
    provenance: dict[str, Any]


def _fixture(tmp_path: Path) -> AdoptionFixture:
    controller_root = tmp_path / "controller"
    controller_root.mkdir()
    owner_root = tmp_path / "owner"
    workspace = tmp_path / "workspace"
    workspace.mkdir()
    source = workspace / "src" / "core.py"
    source.parent.mkdir()
    source.write_text("def run():\n    return 1\n", encoding="utf-8")
    _git(workspace, "init")
    _git(workspace, "config", "user.name", "Adoption Test")
    _git(workspace, "config", "user.email", "adoption@example.test")
    _git(workspace, "add", ".")
    _git(workspace, "commit", "-m", "planned baseline")
    planned_revision = _git(workspace, "rev-parse", "HEAD")
    branch = "backlog/adoption-test"
    _git(workspace, "checkout", "-b", branch)

    case_id = "case:adoption"
    plan_revision_id = "plan:adoption:v1"
    fingerprint = _case_plan_fingerprint(
        case_id=case_id,
        plan_revision_id=plan_revision_id,
    )
    target_contract = build_plan_target_contract(
        {
            "case_id": case_id,
            "problem_id": "problem:adoption",
            "selected_option_id": "option:adoption",
            "repo_revision": planned_revision,
            "change_targets": [
                {
                    "action": "modify",
                    "path": "src/core.py",
                    "symbols": ["core.run"],
                    "change": "Apply the researched behavior at core.run.",
                }
            ],
        },
        repo_root=workspace,
    )
    ticket_path = (
        owner_root / ".agents" / "plans" / "2 - ready" / f"20260715_{fingerprint}_adoption.md"
    )
    ticket_path.parent.mkdir(parents=True)
    ticket_path.write_text(
        "# Adopt existing implementation PR\n\n"
        "Generated by `python -m usertest_backlog.cli reports export-tickets`.\n\n"
        f"- Fingerprint: `{fingerprint}`\n"
        f"- Case ID: `{case_id}`\n"
        f"- Plan revision ID: `{plan_revision_id}`\n"
        "- Export kind: `implementation`\n"
        "- Stage: `ready_for_ticket`\n\n"
        "### Verification command contract\n\n"
        f"{render_verification_contract_markdown(PLAN_COMMANDS)}\n\n"
        "### Machine-verifiable implementation scope contract\n\n"
        f"{render_plan_target_contract_markdown(target_contract)}\n",
        encoding="utf-8",
    )
    selected = _select_ticket_from_path(ticket_path)
    provenance = _selected_ticket_provenance(selected, require_local_plan=True)

    source.write_text("def run():\n    return 2\n", encoding="utf-8")
    _git(workspace, "add", ".")
    _git(workspace, "commit", "-m", "implementation")
    head = _git(workspace, "rev-parse", "HEAD")
    _git(
        workspace,
        "remote",
        "add",
        "github",
        "https://github.com/example/project.git",
    )

    source_run_dir = tmp_path / "source-run"
    source_run_dir.mkdir()
    binding = build_verification_binding(
        ticket_provenance=provenance,
        configured_commands=PLAN_COMMANDS,
    )
    _write_json(
        source_run_dir / "ticket_ref.json",
        {
            "schema_version": 2,
            "fingerprint": fingerprint,
            "case_id": case_id,
            "plan_revision_id": plan_revision_id,
            "ticket_provenance": provenance,
            "verification_binding": binding,
            "owner_repo": {
                "root": str(owner_root),
                "idea_path": str(ticket_path),
            },
        },
    )
    _write_json(
        source_run_dir / "workspace_ref.json",
        {"schema_version": 1, "workspace_dir": str(workspace)},
    )
    _write_json(
        source_run_dir / "target_ref.json",
        {"commit_sha": planned_revision, "ref": branch},
    )
    _write_json(
        source_run_dir / "git_ref.json",
        {
            "schema_version": 1,
            "branch": branch,
            "commit_attempted": True,
            "commit_performed": True,
            "base_commit": planned_revision,
            "head_commit": head,
            "error": None,
        },
    )
    six_commands = [*PLAN_COMMANDS, *EXTRA_COMMANDS]
    _write_json(
        source_run_dir / "verification.json",
        {
            "schema_version": 1,
            "passed": True,
            "status": "passed",
            "terminal_reason": "passed",
            "timed_out": False,
            "cancelled": False,
            "timeout_seconds": 86400.0,
            "python_executable": sys.executable,
            "commands_configured": six_commands,
            "commands": [
                {
                    "command": command,
                    "exit_code": 0,
                    "timed_out": False,
                    "cancelled": False,
                    "dispatch_blocked": False,
                    "rejected_sentinel": False,
                }
                for command in six_commands
            ],
        },
    )
    record_verified_implementation_head(
        run_dir=source_run_dir,
        require_exact_base=True,
    )
    _write_json(
        source_run_dir / "ticket_resume_state.json",
        {
            "schema_version": 1,
            "kind": "ticket_resume_state",
            "ticket": {
                "fingerprint": fingerprint,
                "path": str(ticket_path),
                "title": "Adopt existing implementation PR",
                "export_kind": "implementation",
            },
            "owner_root": str(owner_root),
            "run_dir": str(source_run_dir),
            "workspace_path": str(workspace),
            "branch": branch,
            "pr_url": None,
            "lifecycle_state": "implemented_local",
            "blocking_reason": None,
        },
    )
    runs_root = tmp_path / "runs"
    ledger_path = controller_root / ".agents" / "state" / "ledger.yaml"
    return AdoptionFixture(
        controller_root=controller_root,
        owner_root=owner_root,
        ticket_path=ticket_path,
        workspace=workspace,
        source_run_dir=source_run_dir,
        runs_root=runs_root,
        ledger_path=ledger_path,
        fingerprint=fingerprint,
        case_id=case_id,
        plan_revision_id=plan_revision_id,
        branch=branch,
        planned_revision=planned_revision,
        head=head,
        provenance=provenance,
    )


def _args(fixture: AdoptionFixture) -> SimpleNamespace:
    return SimpleNamespace(
        repo_root=fixture.controller_root,
        owner_root=fixture.owner_root,
        ticket_path=fixture.ticket_path,
        source_run_dir=fixture.source_run_dir,
        runs_dir=fixture.runs_root,
        pr_url=PR_URL,
        base_branch="dev",
        remote_name="github",
        ledger=Path(".agents/state/ledger.yaml"),
    )


def _pr_context(
    fixture: AdoptionFixture,
    *,
    head: str | None = None,
    base: str | None = None,
) -> dict[str, Any]:
    return {
        "pr": {
            "number": 213,
            "url": PR_URL,
            "title": "Adopt implementation",
            "state": "OPEN",
            "isDraft": True,
            "headRefName": fixture.branch,
            "headRefOid": head or fixture.head,
            "baseRefName": "dev",
            "baseRefOid": base or fixture.planned_revision,
        },
        "checks": [],
        "ci_status": "pending",
        "ci_conclusion": None,
        "changed_files": ["src/core.py"],
        "diff_full": "",
        "diff_excerpt": "",
        "diff_truncated": False,
    }


def _install_fake_capture(
    monkeypatch: pytest.MonkeyPatch,
    *,
    fixture: AdoptionFixture,
    calls: list[dict[str, Any]],
) -> None:
    def _capture(**kwargs: Any) -> dict[str, Any]:
        calls.append(dict(kwargs))
        assert kwargs["cwd"] == fixture.workspace.resolve()
        assert kwargs["commands"] == PLAN_COMMANDS
        assert kwargs["timeout_seconds"] == 86400.0
        run_dir = Path(kwargs["run_dir"])
        capture_dir = run_dir / "verification" / "capture"
        capture_dir.mkdir(parents=True)
        results = []
        for index, command in enumerate(PLAN_COMMANDS, start=1):
            stdout_path = capture_dir / f"cmd_{index:02d}.stdout.txt"
            stderr_path = capture_dir / f"cmd_{index:02d}.stderr.txt"
            stdout_path.write_text("passed\n", encoding="utf-8")
            stderr_path.write_text("", encoding="utf-8")
            results.append(
                {
                    "command": command,
                    "exit_code": 0,
                    "timed_out": False,
                    "cancelled": False,
                    "dispatch_blocked": False,
                    "rejected_sentinel": False,
                    "stdout_path": stdout_path.name,
                    "stderr_path": stderr_path.name,
                }
            )
        verification = {
            "schema_version": 1,
            "passed": True,
            "status": "passed",
            "terminal_reason": "passed",
            "timed_out": False,
            "cancelled": False,
            "timeout_seconds": 86400.0,
            "python_executable": kwargs["python_executable"],
            "commands_configured": list(PLAN_COMMANDS),
            "commands": results,
            "model_invoked": False,
            "workspace_mirror_written": False,
        }
        _write_json(run_dir / "verification.json", verification)
        return verification

    monkeypatch.setattr(handoff_commands, "capture_local_verification", _capture)


def test_adopt_pr_rejects_six_command_superset_then_captures_exact_two_commands(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    fixture = _fixture(tmp_path)
    original_ticket = fixture.ticket_path.read_bytes()
    original_source = {
        path.name: path.read_bytes() for path in fixture.source_run_dir.iterdir() if path.is_file()
    }
    with pytest.raises(ValueError, match="selected plan contract"):
        validate_bound_runner_verification(
            run_dir=fixture.source_run_dir,
            fingerprint=fixture.fingerprint,
            case_id=fixture.case_id,
            plan_revision_id=fixture.plan_revision_id,
            evidence_kind="test",
            owner_root=fixture.owner_root,
            expected_ticket_provenance=fixture.provenance,
        )

    contexts: list[str] = []

    def _context(**_: Any) -> dict[str, Any]:
        contexts.append("read")
        return _pr_context(fixture)

    monkeypatch.setattr(handoff_commands, "_collect_pr_review_context", _context)
    capture_calls: list[dict[str, Any]] = []
    _install_fake_capture(monkeypatch, fixture=fixture, calls=capture_calls)

    assert handoff_commands._cmd_handoff_adopt_pr(_args(fixture)) == 0

    payload = json.loads(capsys.readouterr().out)
    derived_run = Path(payload["run_dir"])
    verification = json.loads((derived_run / "verification.json").read_text(encoding="utf-8"))
    receipt = json.loads((derived_run / "verification_receipt.json").read_text(encoding="utf-8"))
    capture_ref = json.loads(
        (derived_run / "verification_capture_ref.json").read_text(encoding="utf-8")
    )
    pr_ref = json.loads((derived_run / "pr_ref.json").read_text(encoding="utf-8"))
    resume_state = json.loads(
        (derived_run / "ticket_resume_state.json").read_text(encoding="utf-8")
    )
    ledger = yaml.safe_load(fixture.ledger_path.read_text(encoding="utf-8"))
    ledger_entry = ledger["actions"][fixture.fingerprint]

    assert len(contexts) == 2
    assert len(capture_calls) == 1
    assert verification["commands_configured"] == PLAN_COMMANDS
    assert [item["command"] for item in verification["commands"]] == PLAN_COMMANDS
    assert receipt["commands"] == PLAN_COMMANDS
    assert capture_ref["source_exact_plan_receipt"] is False
    assert capture_ref["capture_performed"] is True
    assert capture_ref["model_invoked"] is False
    assert (derived_run / "verification" / "capture" / "cmd_01.stdout.txt").is_file()
    assert (derived_run / "verification" / "capture" / "cmd_02.stderr.txt").is_file()
    assert pr_ref["created"] is False
    assert pr_ref["pr_adopted"] is True
    assert pr_ref["created_by_command"] is False
    assert resume_state["lifecycle_state"] == "awaiting_review"
    assert ledger_entry["last_run_dir"] == str(derived_run)
    assert ledger_entry["pr_adopted"] is True
    assert ledger_entry["last_resume_state_path"] == str(derived_run / "ticket_resume_state.json")
    assert ledger_entry["last_resume_lifecycle_state"] == "awaiting_review"
    assert "outcome" not in ledger_entry
    assert fixture.ticket_path.read_bytes() == original_ticket
    assert fixture.ticket_path.parent.name == "2 - ready"
    assert {
        path.name: path.read_bytes() for path in fixture.source_run_dir.iterdir() if path.is_file()
    } == original_source
    assert not (derived_run / "raw_events.jsonl").exists()
    assert not (derived_run / "agent_attempts.json").exists()
    assert payload["model_invoked"] is False


def test_adopt_pr_rejects_dirty_workspace_before_pr_or_capture(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    fixture = _fixture(tmp_path)
    fixture_ticket = fixture.ticket_path.read_bytes()
    (fixture.workspace / "dirty.txt").write_text("dirty\n", encoding="utf-8")
    monkeypatch.setattr(
        handoff_commands,
        "_collect_pr_review_context",
        lambda **_: pytest.fail("PR must not be read for a dirty workspace"),
    )
    monkeypatch.setattr(
        handoff_commands,
        "capture_local_verification",
        lambda **_: pytest.fail("verification must not run for a dirty workspace"),
    )

    with pytest.raises(SystemExit, match="workspace_dirty"):
        handoff_commands._cmd_handoff_adopt_pr(_args(fixture))

    assert fixture.ticket_path.read_bytes() == fixture_ticket
    assert not fixture.runs_root.exists()


def test_adopt_pr_rejects_arbitrary_descendant_before_capture(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    fixture = _fixture(tmp_path)
    (fixture.workspace / "src" / "core.py").write_text(
        "def run():\n    return 3\n", encoding="utf-8"
    )
    _git(fixture.workspace, "add", ".")
    _git(fixture.workspace, "commit", "-m", "unexpected later head")
    unexpected_head = _git(fixture.workspace, "rev-parse", "HEAD")
    monkeypatch.setattr(
        handoff_commands,
        "_collect_pr_review_context",
        lambda **_: _pr_context(fixture, head=unexpected_head),
    )
    monkeypatch.setattr(
        handoff_commands,
        "capture_local_verification",
        lambda **_: pytest.fail("verification must not run for an arbitrary descendant"),
    )

    with pytest.raises(SystemExit, match="descendant_not_current_base_merge"):
        handoff_commands._cmd_handoff_adopt_pr(_args(fixture))

    assert not fixture.runs_root.exists()


def test_adopt_pr_reuses_verification_after_runner_owned_cleanup(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    fixture = _fixture(tmp_path)
    verification_path = fixture.source_run_dir / "verification.json"
    verification = json.loads(verification_path.read_text(encoding="utf-8"))
    verification["commands_configured"] = PLAN_COMMANDS
    verification["commands"] = verification["commands"][: len(PLAN_COMMANDS)]
    _write_json(verification_path, verification)
    runtime_file = (
        fixture.workspace
        / ".usertest_outcome"
        / "controlled"
        / "report.json"
    )
    runtime_file.parent.mkdir(parents=True)
    runtime_file.write_text('{"status":"mitigated"}\n', encoding="utf-8")
    _git(fixture.workspace, "add", ".usertest_outcome")
    _git(fixture.workspace, "commit", "-m", "historical runner output")
    verified_runtime_head = _git(fixture.workspace, "rev-parse", "HEAD")

    git_ref_path = fixture.source_run_dir / "git_ref.json"
    git_ref = json.loads(git_ref_path.read_text(encoding="utf-8"))
    git_ref["head_commit"] = verified_runtime_head
    _write_json(git_ref_path, git_ref)
    ticket_ref_path = fixture.source_run_dir / "ticket_ref.json"
    ticket_ref = json.loads(ticket_ref_path.read_text(encoding="utf-8"))
    ticket_ref.pop("implementation_provenance", None)
    _write_json(ticket_ref_path, ticket_ref)
    record_verified_implementation_head(
        run_dir=fixture.source_run_dir,
        require_exact_base=True,
    )

    _git(fixture.workspace, "rm", "-r", "--cached", ".usertest_outcome")
    _git(fixture.workspace, "commit", "-m", "untrack runner output")
    cleaned_head = _git(fixture.workspace, "rev-parse", "HEAD")
    assert runtime_file.is_file()
    assert "?? .usertest_outcome/" in _git(fixture.workspace, "status", "--short")

    monkeypatch.setattr(
        handoff_commands,
        "_collect_pr_review_context",
        lambda **_: _pr_context(fixture, head=cleaned_head),
    )
    monkeypatch.setattr(
        handoff_commands,
        "capture_local_verification",
        lambda **_: pytest.fail("product-identical cleanup must reuse verification"),
    )

    assert handoff_commands._cmd_handoff_adopt_pr(_args(fixture)) == 0

    payload = json.loads(capsys.readouterr().out)
    derived_run = Path(payload["run_dir"])
    ticket_ref = json.loads((derived_run / "ticket_ref.json").read_text(encoding="utf-8"))
    assert payload["source_verification_reused"] is True
    assert payload["exact_plan_verification_captured"] is False
    assert payload["head_relation"] == {
        "kind": "runner_owned_cleanup",
        "source_head": verified_runtime_head,
        "adopted_head": cleaned_head,
        "pr_base_oid": fixture.planned_revision,
        "paths": [".usertest_outcome/controlled/report.json"],
        "verification_reuse_allowed": True,
    }
    assert ticket_ref["implementation_provenance"]["verified_implementation_head"] == cleaned_head
    assert runtime_file.is_file()


def test_adopt_pr_recaptures_exact_plan_verification_after_current_base_merge(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    fixture = _fixture(tmp_path)
    original_source = {
        path.name: path.read_bytes() for path in fixture.source_run_dir.iterdir() if path.is_file()
    }
    source_state_path = fixture.source_run_dir / "ticket_resume_state.json"
    source_state = json.loads(source_state_path.read_text(encoding="utf-8"))
    source_state["lifecycle_state"] = "ci_failed"
    _write_json(source_state_path, source_state)
    original_source["ticket_resume_state.json"] = source_state_path.read_bytes()

    _git(fixture.workspace, "checkout", "-b", "dev", fixture.planned_revision)
    (fixture.workspace / "base-fix.txt").write_text("portable base fix\n", encoding="utf-8")
    _git(fixture.workspace, "add", ".")
    _git(fixture.workspace, "commit", "-m", "repair base")
    base_head = _git(fixture.workspace, "rev-parse", "HEAD")
    _git(fixture.workspace, "checkout", fixture.branch)
    _git(fixture.workspace, "merge", "--no-ff", "dev", "-m", "merge repaired base")
    refreshed_head = _git(fixture.workspace, "rev-parse", "HEAD")

    contexts: list[str] = []

    def _context(**_: Any) -> dict[str, Any]:
        contexts.append("read")
        return _pr_context(fixture, head=refreshed_head, base=base_head)

    monkeypatch.setattr(handoff_commands, "_collect_pr_review_context", _context)
    capture_calls: list[dict[str, Any]] = []
    _install_fake_capture(monkeypatch, fixture=fixture, calls=capture_calls)

    assert handoff_commands._cmd_handoff_adopt_pr(_args(fixture)) == 0

    payload = json.loads(capsys.readouterr().out)
    derived_run = Path(payload["run_dir"])
    capture_ref = json.loads(
        (derived_run / "verification_capture_ref.json").read_text(encoding="utf-8")
    )
    ticket_ref = json.loads((derived_run / "ticket_ref.json").read_text(encoding="utf-8"))
    provenance = ticket_ref["implementation_provenance"]

    assert len(contexts) == 2
    assert len(capture_calls) == 1
    assert payload["source_verification_reused"] is False
    assert payload["exact_plan_verification_captured"] is True
    assert payload["source_head_commit"] == fixture.head
    assert payload["head_commit"] == refreshed_head
    assert payload["source_lifecycle_state"] == "ci_failed"
    assert payload["head_relation"] == {
        "kind": "current_base_merge",
        "source_head": fixture.head,
        "adopted_head": refreshed_head,
        "pr_base_oid": base_head,
        "parents": [fixture.head, base_head],
        "verification_reuse_allowed": False,
    }
    assert capture_ref["capture_performed"] is True
    assert capture_ref["head_relation"] == payload["head_relation"]
    assert provenance["verified_implementation_head"] == refreshed_head
    assert {
        path.name: path.read_bytes() for path in fixture.source_run_dir.iterdir() if path.is_file()
    } == original_source


def test_adopt_pr_rejects_pr_head_mismatch_before_capture(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    fixture = _fixture(tmp_path)
    monkeypatch.setattr(
        handoff_commands,
        "_collect_pr_review_context",
        lambda **_: _pr_context(fixture, head=fixture.planned_revision),
    )
    monkeypatch.setattr(
        handoff_commands,
        "capture_local_verification",
        lambda **_: pytest.fail("verification must not run for a mismatched PR"),
    )

    with pytest.raises(SystemExit, match="pr_head_mismatch"):
        handoff_commands._cmd_handoff_adopt_pr(_args(fixture))

    assert not fixture.runs_root.exists()


def test_adopt_pr_rejects_pr_movement_during_exact_verification(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    fixture = _fixture(tmp_path)
    ticket_bytes = fixture.ticket_path.read_bytes()
    contexts = [
        _pr_context(fixture),
        _pr_context(fixture, head=fixture.planned_revision),
    ]
    monkeypatch.setattr(
        handoff_commands,
        "_collect_pr_review_context",
        lambda **_: contexts.pop(0),
    )
    capture_calls: list[dict[str, Any]] = []
    _install_fake_capture(monkeypatch, fixture=fixture, calls=capture_calls)

    with pytest.raises(SystemExit, match="pr_head_mismatch"):
        handoff_commands._cmd_handoff_adopt_pr(_args(fixture))

    assert len(capture_calls) == 1
    assert fixture.ticket_path.read_bytes() == ticket_bytes
    assert not fixture.ledger_path.exists()
