from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Sequence
from pathlib import Path
from typing import Any

_GENERATED_TICKET_MARKER = (
    "Generated by `python -m usertest_backlog.cli reports export-tickets`"
)
_LEGACY_GENERATED_TICKET_MARKER = (
    "Generated by `python -m usertest.cli reports export-tickets`"
)
_OUTCOME_BLOCK_RE = re.compile(
    r"\n?<!-- backlog-outcome:start -->.*?<!-- backlog-outcome:end -->\n?",
    flags=re.DOTALL,
)
_VERIFICATION_CONTRACT_RE = re.compile(
    r"<!-- backlog-verification-contract:start -->\s*"
    r"```json\s*(?P<payload>\{.*?\})\s*```\s*"
    r"<!-- backlog-verification-contract:end -->",
    flags=re.DOTALL,
)
_OUTCOME_ROLES = (
    "original_scenario",
    "live",
    "mitigation_effect",
    "recurrence",
)
_GENERIC_TEST_TOKENS = re.compile(
    r"(?:^|[\s/\\])(?:pytest|unittest|ruff|mypy|pyright|eslint|jest|vitest|cargo\s+test|go\s+test)(?:\s|$)",
    flags=re.IGNORECASE,
)


def _canonical_json(value: Any) -> str:
    return json.dumps(
        value,
        sort_keys=True,
        ensure_ascii=False,
        separators=(",", ":"),
    )


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _normalize_markdown(value: str) -> str:
    normalized = value.replace("\r\n", "\n").replace("\r", "\n")
    return normalized.rstrip() + "\n"


def canonical_plan_markdown(markdown: str) -> str:
    """Return the immutable plan portion used for provenance hashing.

    Outcome records and the legacy source-ticket pointer are lifecycle metadata;
    moving a plan to another queue or appending an outcome must not invalidate
    the implementation provenance captured when the plan was selected.
    """

    without_outcome = _OUTCOME_BLOCK_RE.sub("\n", markdown)
    without_legacy_source = re.sub(
        r"(?m)^-\s*Source ticket:\s*`[^`]*`\s*$\n?",
        "",
        without_outcome,
    )
    return _normalize_markdown(without_legacy_source)


def canonical_ticket_body(markdown: str) -> str:
    """Return the exported issue body embedded in a generated local plan.

    Generated queue files wrap the exported body in a title, timestamp, routing
    metadata, and (optionally) a UX-review preface. This projection removes only
    that generated wrapper so the JSON export and referenced local plan can be
    compared byte-for-byte after newline normalization.
    """

    plan = canonical_plan_markdown(markdown)
    lines = plan.splitlines()
    marker_indexes = [
        index for index, line in enumerate(lines) if _GENERATED_TICKET_MARKER in line
    ]
    if not marker_indexes:
        return plan
    if len(marker_indexes) != 1:
        raise ValueError("ticket_provenance_generated_marker_ambiguous")

    marker_index = marker_indexes[0]
    heading_index: int | None = None
    for index in range(marker_index - 1, -1, -1):
        if not lines[index].strip():
            continue
        if lines[index].startswith("# "):
            heading_index = index
            break
        raise ValueError("ticket_provenance_generated_heading_invalid")
    if heading_index is None:
        raise ValueError("ticket_provenance_generated_heading_missing")

    body_index: int | None = None
    for index in range(marker_index + 1, len(lines)):
        if not lines[index].strip():
            body_index = index + 1
            break
    if body_index is None or body_index >= len(lines):
        raise ValueError("ticket_provenance_generated_body_missing")

    prefix = "\n".join(lines[:heading_index]).strip()
    body = "\n".join(lines[body_index:]).strip()
    if not body:
        raise ValueError("ticket_provenance_generated_body_empty")
    combined = f"{prefix}\n\n{body}" if prefix else body
    return _normalize_markdown(combined)


def canonical_plan_sha256(markdown: str) -> str:
    return sha256_text(canonical_plan_markdown(markdown))


def canonical_ticket_body_sha256(markdown: str) -> str:
    return sha256_text(canonical_ticket_body(markdown))


def normalize_verification_commands(commands: Sequence[str]) -> list[str]:
    normalized: list[str] = []
    for index, command in enumerate(commands):
        if not isinstance(command, str) or not command.strip():
            raise ValueError(
                f"verification_contract_command_invalid: commands[{index}]"
            )
        normalized.append(command.strip())
    if not normalized:
        raise ValueError("verification_contract_commands_empty")
    if len(normalized) != len(set(normalized)):
        raise ValueError("verification_contract_commands_duplicate")
    return normalized


def verification_commands_sha256(commands: Sequence[str]) -> str:
    normalized = normalize_verification_commands(commands)
    return sha256_text(
        _canonical_json({"schema_version": 1, "commands": normalized})
    )


def _normalize_role_predicate(
    raw: Any,
    *,
    role: str,
    index: int,
    command_count: int,
    oracle_target_ids: set[str] | None = None,
    oracle_scenario_ids: list[str] | None = None,
) -> dict[str, Any]:
    if not isinstance(raw, dict):
        raise ValueError(f"outcome_role_predicate_invalid: {role}[{index}]")
    predicate_type = raw.get("type")
    if predicate_type == "command_exit_code":
        allowed = {"type", "command_index", "equals"}
        command_index = raw.get("command_index")
        equals = raw.get("equals")
        if (
            isinstance(command_index, bool)
            or not isinstance(command_index, int)
            or command_index < 0
            or command_index >= command_count
            or isinstance(equals, bool)
            or not isinstance(equals, int)
        ):
            raise ValueError(f"outcome_role_exit_predicate_invalid: {role}[{index}]")
        normalized = {
            "type": predicate_type,
            "command_index": command_index,
            "equals": equals,
        }
    elif predicate_type == "command_stdout_contains":
        allowed = {"type", "command_index", "value"}
        command_index = raw.get("command_index")
        value = raw.get("value")
        if (
            isinstance(command_index, bool)
            or not isinstance(command_index, int)
            or command_index < 0
            or command_index >= command_count
            or not isinstance(value, str)
            or not value.strip()
        ):
            raise ValueError(f"outcome_role_stdout_predicate_invalid: {role}[{index}]")
        normalized = {
            "type": predicate_type,
            "command_index": command_index,
            "value": value.strip(),
        }
    elif predicate_type == "artifact_json_value":
        allowed = {"type", "path", "json_pointer", "equals"}
        path_raw = raw.get("path")
        pointer = raw.get("json_pointer")
        if not isinstance(path_raw, str) or not path_raw.strip():
            raise ValueError(f"outcome_role_artifact_path_invalid: {role}[{index}]")
        path = Path(path_raw.strip())
        if path.is_absolute() or ".." in path.parts:
            raise ValueError(f"outcome_role_artifact_path_unsafe: {role}[{index}]")
        if not isinstance(pointer, str) or (pointer and not pointer.startswith("/")):
            raise ValueError(f"outcome_role_json_pointer_invalid: {role}[{index}]")
        normalized = {
            "type": predicate_type,
            "path": path.as_posix(),
            "json_pointer": pointer,
            "equals": raw.get("equals"),
        }
    elif predicate_type == "oracle_state_equals":
        allowed = {"type", "target_id", "exists", "equals"}
        target_id = raw.get("target_id")
        exists = raw.get("exists")
        if (
            not isinstance(target_id, str)
            or not target_id.strip()
            or target_id not in (oracle_target_ids or set())
            or not isinstance(exists, bool)
            or "equals" not in raw
        ):
            raise ValueError(f"outcome_role_state_predicate_invalid: {role}[{index}]")
        normalized = {
            "type": predicate_type,
            "target_id": target_id.strip(),
            "exists": exists,
            "equals": raw.get("equals"),
        }
    elif predicate_type == "oracle_scenario_passed":
        allowed = {"type", "scenario_index", "scenario_id"}
        scenario_index = raw.get("scenario_index")
        scenario_id = raw.get("scenario_id")
        if (
            isinstance(scenario_index, bool)
            or not isinstance(scenario_index, int)
            or scenario_index < 0
            or not isinstance(oracle_scenario_ids, list)
            or scenario_index >= len(oracle_scenario_ids)
            or not isinstance(scenario_id, str)
            or scenario_id != oracle_scenario_ids[scenario_index]
        ):
            raise ValueError(f"outcome_role_scenario_predicate_invalid: {role}[{index}]")
        normalized = {
            "type": predicate_type,
            "scenario_index": scenario_index,
            "scenario_id": scenario_id,
        }
    else:
        raise ValueError(f"outcome_role_predicate_type_invalid: {role}[{index}]")
    unknown = sorted(set(raw) - allowed)
    if unknown:
        raise ValueError(f"outcome_role_predicate_unknown_fields: {role}[{index}]: {unknown!r}")
    return normalized


def _normalize_outcome_oracle(raw: Any) -> dict[str, Any]:
    if not isinstance(raw, dict):
        raise ValueError("outcome_role_oracle_invalid")
    oracle_id = raw.get("outcome_oracle_id")
    projection = {key: value for key, value in raw.items() if key != "outcome_oracle_id"}
    expected_id = f"outcome_oracle:{sha256_text(_canonical_json(projection))}"
    if oracle_id != expected_id or raw.get("schema_version") != 1:
        raise ValueError("outcome_role_oracle_hash_invalid")
    kind = raw.get("kind")
    proof_scope = raw.get("proof_scope")
    if kind == "staged_replay":
        execution = raw.get("execution")
        argv = execution.get("argv") if isinstance(execution, dict) else None
        authorization = (
            execution.get("command_authorization")
            if isinstance(execution, dict)
            else None
        )
        if (
            proof_scope != "behavioral"
            or not isinstance(execution, dict)
            or execution.get("shell") is not False
            or not isinstance(argv, list)
            or not argv
            or not isinstance(authorization, dict)
            or authorization.get("authorization_kind")
            not in {
                "standard_test_or_research_harness",
                "immutable_source_command",
                "declared_inspected_repository_entrypoint",
            }
            or authorization.get("executed_argv_sha256")
            != sha256_text(_canonical_json(argv))
            or authorization.get("shell") is not False
            or authorization.get("workspace_confined") is not True
        ):
            raise ValueError("outcome_role_replay_oracle_invalid")
    elif kind == "config_state":
        targets = raw.get("state_targets")
        if proof_scope != "configuration_state" or not isinstance(targets, list) or not targets:
            raise ValueError("outcome_role_config_oracle_invalid")
    elif kind == "multi_scenario":
        scenarios = raw.get("scenarios")
        contracts = raw.get("positive_outcome_contracts")
        contract_ids = {
            contract.get("positive_outcome_contract_id")
            for contract in contracts if isinstance(contract, dict)
        } if isinstance(contracts, list) else set()
        if (
            proof_scope != "multi_scenario"
            or not isinstance(scenarios, list)
            or len(scenarios) < 2
            or not contract_ids
        ):
            raise ValueError("outcome_role_multi_scenario_oracle_invalid")
        observed_ids: set[str] = set()
        for index, scenario in enumerate(scenarios):
            if not isinstance(scenario, dict):
                raise ValueError(f"outcome_role_multi_scenario_invalid:{index}")
            scenario_id = scenario.get("scenario_id")
            scenario_projection = {
                key: value for key, value in scenario.items() if key != "scenario_id"
            }
            selected_id = scenario.get("positive_outcome_contract_id")
            child = _normalize_outcome_oracle(scenario.get("oracle"))
            child_contracts = child.get("positive_outcome_contracts")
            child_ids = {
                contract.get("positive_outcome_contract_id")
                for contract in child_contracts if isinstance(contract, dict)
            } if isinstance(child_contracts, list) else set()
            predicates = scenario.get("predicates")
            if (
                scenario_id
                != f"outcome_scenario:{sha256_text(_canonical_json(scenario_projection))}"
                or child.get("kind") == "multi_scenario"
                or selected_id not in contract_ids
                or selected_id not in child_ids
                or selected_id in observed_ids
                or not isinstance(predicates, list)
                or not predicates
            ):
                raise ValueError(f"outcome_role_multi_scenario_invalid:{index}")
            observed_ids.add(str(selected_id))
        if observed_ids != contract_ids:
            raise ValueError("outcome_role_multi_scenario_contract_coverage_invalid")
    else:
        raise ValueError("outcome_role_oracle_kind_invalid")
    return dict(raw)


def normalize_outcome_role_contracts(
    raw: Any,
    *,
    test_commands: Sequence[str],
) -> dict[str, dict[str, Any] | None]:
    """Normalize role-specific, machine-evaluated post-merge proof contracts."""

    if not isinstance(raw, dict):
        raise ValueError("outcome_role_contracts_invalid")
    missing = sorted(set(_OUTCOME_ROLES) - set(raw))
    unknown = sorted(set(raw) - set(_OUTCOME_ROLES))
    if missing or unknown:
        raise ValueError(
            f"outcome_role_contract_fields_invalid: missing={missing!r} unknown={unknown!r}"
        )
    generic_commands = set(normalize_verification_commands(test_commands))
    normalized: dict[str, dict[str, Any] | None] = {}
    for role in _OUTCOME_ROLES:
        value = raw.get(role)
        if value is None:
            normalized[role] = None
            continue
        if not isinstance(value, dict):
            raise ValueError(f"outcome_role_contract_invalid: {role}")
        allowed = {
            "description",
            "commands",
            "predicates",
            "research_experiment_id",
            "research_experiment_ids",
            "selected_positive_outcome_contract_ids",
            "oracle",
            "required_proof_scope",
            "role_contract_sha256",
        }
        unknown_fields = sorted(set(value) - allowed)
        if unknown_fields:
            raise ValueError(
                f"outcome_role_contract_unknown_fields: {role}: {unknown_fields!r}"
            )
        description = value.get("description")
        if not isinstance(description, str) or not description.strip():
            raise ValueError(f"outcome_role_description_invalid: {role}")
        oracle_raw = value.get("oracle")
        if oracle_raw is not None and role != "original_scenario":
            raise ValueError(f"outcome_role_oracle_forbidden: {role}")
        oracle = _normalize_outcome_oracle(oracle_raw) if oracle_raw is not None else None
        oracle_kind = oracle.get("kind") if oracle is not None else None
        proof_scope = value.get("required_proof_scope")
        if oracle is not None and proof_scope != oracle.get("proof_scope"):
            raise ValueError("outcome_role_oracle_scope_mismatch")
        if oracle is None and proof_scope is not None:
            raise ValueError(f"outcome_role_scope_without_oracle: {role}")
        commands_raw = value.get("commands")
        if not isinstance(commands_raw, list):
            raise ValueError(f"outcome_role_commands_invalid: {role}")
        if oracle is not None:
            if commands_raw:
                raise ValueError("outcome_role_oracle_commands_forbidden")
            commands = []
        elif role == "recurrence" and not commands_raw:
            commands = []
        else:
            commands = normalize_verification_commands(commands_raw)
        if role in {"live", "mitigation_effect", "recurrence"}:
            if generic_commands.intersection(commands):
                raise ValueError(f"outcome_role_generic_command_reused: {role}")
            if any(_GENERIC_TEST_TOKENS.search(command) for command in commands):
                raise ValueError(f"outcome_role_generic_test_forbidden: {role}")
        predicates_raw = value.get("predicates")
        if not isinstance(predicates_raw, list) or (
            not predicates_raw and role != "recurrence"
        ):
            raise ValueError(f"outcome_role_predicates_invalid: {role}")
        oracle_target_ids = {
            str(target.get("target_id"))
            for target in (oracle.get("state_targets", []) if oracle is not None else [])
            if isinstance(target, dict) and isinstance(target.get("target_id"), str)
        }
        oracle_scenario_ids = [
            str(scenario.get("scenario_id"))
            for scenario in (oracle.get("scenarios", []) if oracle is not None else [])
            if isinstance(scenario, dict) and isinstance(scenario.get("scenario_id"), str)
        ]
        command_count = 1 if oracle_kind == "staged_replay" else len(commands)
        predicates = [
            _normalize_role_predicate(
                predicate,
                role=role,
                index=index,
                command_count=command_count,
                oracle_target_ids=oracle_target_ids,
                oracle_scenario_ids=oracle_scenario_ids,
            )
            for index, predicate in enumerate(predicates_raw)
        ]
        exit_covered = {
            predicate["command_index"]
            for predicate in predicates
            if predicate["type"] == "command_exit_code"
        }
        expected_exit_covered = {0} if oracle_kind == "staged_replay" else set(range(len(commands)))
        if exit_covered != expected_exit_covered:
            raise ValueError(f"outcome_role_exit_predicate_coverage_invalid: {role}")
        if oracle_kind == "config_state":
            state_covered = {
                predicate["target_id"]
                for predicate in predicates
                if predicate["type"] == "oracle_state_equals"
            }
            if state_covered != oracle_target_ids:
                raise ValueError("outcome_role_state_predicate_coverage_invalid")
        if oracle_kind == "multi_scenario":
            scenario_covered = [
                predicate["scenario_id"]
                for predicate in predicates
                if predicate["type"] == "oracle_scenario_passed"
            ]
            if scenario_covered != oracle_scenario_ids:
                raise ValueError("outcome_role_scenario_predicate_coverage_invalid")
        research_experiment_id = value.get("research_experiment_id")
        research_experiment_ids = value.get("research_experiment_ids")
        selected_contract_ids = value.get("selected_positive_outcome_contract_ids")
        if role == "original_scenario":
            if not isinstance(research_experiment_id, str) or not research_experiment_id.strip():
                raise ValueError("outcome_role_research_experiment_id_required")
            if (
                oracle is not None
                and oracle_kind != "multi_scenario"
                and oracle.get("research_experiment_id") != (
                research_experiment_id.strip()
                )
            ):
                raise ValueError("outcome_role_oracle_experiment_mismatch")
            normalized_experiment_ids = (
                research_experiment_ids
                if isinstance(research_experiment_ids, list)
                else [research_experiment_id.strip()]
            )
            if (
                not normalized_experiment_ids
                or any(
                    not isinstance(value, str) or not value.strip()
                    for value in normalized_experiment_ids
                )
                or normalized_experiment_ids[0] != research_experiment_id.strip()
            ):
                raise ValueError("outcome_role_research_experiment_ids_invalid")
            oracle_contract_ids = {
                contract.get("positive_outcome_contract_id")
                for contract in (
                    oracle.get("positive_outcome_contracts", [])
                    if isinstance(oracle, dict)
                    else []
                )
                if isinstance(contract, dict)
            }
            normalized_selected_ids = (
                selected_contract_ids
                if isinstance(selected_contract_ids, list)
                else list(oracle_contract_ids)
                if len(oracle_contract_ids) == 1
                else []
            )
            if oracle is not None and (
                not normalized_selected_ids
                or len(normalized_selected_ids) != len(set(normalized_selected_ids))
                or any(value not in oracle_contract_ids for value in normalized_selected_ids)
                or (
                    oracle_kind == "multi_scenario"
                    and set(normalized_selected_ids) != oracle_contract_ids
                )
                or (
                    oracle_kind != "multi_scenario"
                    and len(normalized_selected_ids) != 1
                )
            ):
                raise ValueError("outcome_role_selected_positive_contract_ids_invalid")
            if oracle is None and selected_contract_ids is not None:
                raise ValueError("outcome_role_selected_positive_contract_without_oracle")
        elif research_experiment_id is not None:
            raise ValueError(f"outcome_role_research_experiment_id_forbidden: {role}")
        elif research_experiment_ids is not None or selected_contract_ids is not None:
            raise ValueError(f"outcome_role_original_scenario_fields_forbidden: {role}")
        role_payload: dict[str, Any] = {
            "description": description.strip(),
            "commands": commands,
            "predicates": predicates,
        }
        if role == "original_scenario":
            role_payload["research_experiment_id"] = research_experiment_id.strip()
            if research_experiment_ids is not None:
                role_payload["research_experiment_ids"] = [
                    value.strip() for value in normalized_experiment_ids
                ]
            if selected_contract_ids is not None:
                role_payload["selected_positive_outcome_contract_ids"] = list(
                    normalized_selected_ids
                )
            if oracle is not None:
                role_payload["oracle"] = oracle
                role_payload["required_proof_scope"] = proof_scope
        role_hash = sha256_text(_canonical_json(role_payload))
        supplied_role_hash = value.get("role_contract_sha256")
        if supplied_role_hash is not None and supplied_role_hash != role_hash:
            raise ValueError(f"outcome_role_contract_hash_mismatch: {role}")
        normalized[role] = {**role_payload, "role_contract_sha256": role_hash}
    if normalized["original_scenario"] is None:
        raise ValueError("outcome_role_original_scenario_required")
    if normalized["recurrence"] is None:
        raise ValueError("outcome_role_recurrence_required")
    return normalized


def verification_contract_payload(
    commands: Sequence[str],
    *,
    outcome_roles: Any | None = None,
) -> dict[str, Any]:
    normalized = normalize_verification_commands(commands)
    if outcome_roles is None:
        return {
            "schema_version": 1,
            "commands": normalized,
            "contract_sha256": verification_commands_sha256(normalized),
        }
    normalized_roles = normalize_outcome_role_contracts(
        outcome_roles,
        test_commands=normalized,
    )
    unsigned = {
        "schema_version": 2,
        "commands": normalized,
        "outcome_roles": normalized_roles,
    }
    return {**unsigned, "contract_sha256": sha256_text(_canonical_json(unsigned))}


def render_verification_contract_markdown(
    commands: Sequence[str],
    *,
    outcome_roles: Any | None = None,
) -> str:
    payload = verification_contract_payload(commands, outcome_roles=outcome_roles)
    rendered = json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True)
    return (
        "<!-- backlog-verification-contract:start -->\n"
        "```json\n"
        f"{rendered}\n"
        "```\n"
        "<!-- backlog-verification-contract:end -->"
    )


def parse_verification_contract_markdown(markdown: str) -> dict[str, Any] | None:
    matches = list(_VERIFICATION_CONTRACT_RE.finditer(markdown))
    if not matches:
        return None
    if len(matches) != 1:
        raise ValueError("verification_contract_block_ambiguous")
    try:
        payload = json.loads(matches[0].group("payload"))
    except json.JSONDecodeError as exc:
        raise ValueError("verification_contract_json_invalid") from exc
    if not isinstance(payload, dict):
        raise ValueError("verification_contract_payload_invalid")
    allowed = {"schema_version", "commands", "outcome_roles", "contract_sha256"}
    unknown = sorted(set(payload) - allowed)
    if unknown:
        raise ValueError(f"verification_contract_unknown_fields: {unknown!r}")
    if payload.get("schema_version") not in {1, 2}:
        raise ValueError("verification_contract_schema_version_invalid")
    commands_raw = payload.get("commands")
    if not isinstance(commands_raw, list):
        raise ValueError("verification_contract_commands_invalid")
    commands = normalize_verification_commands(commands_raw)
    if payload.get("schema_version") == 1:
        if "outcome_roles" in payload:
            raise ValueError("verification_contract_v1_outcome_roles_forbidden")
        expected_hash = verification_commands_sha256(commands)
        if payload.get("contract_sha256") != expected_hash:
            raise ValueError("verification_contract_hash_mismatch")
        return {
            "schema_version": 1,
            "commands": commands,
            "contract_sha256": expected_hash,
        }
    roles = normalize_outcome_role_contracts(
        payload.get("outcome_roles"),
        test_commands=commands,
    )
    unsigned = {"schema_version": 2, "commands": commands, "outcome_roles": roles}
    expected_hash = sha256_text(_canonical_json(unsigned))
    if payload.get("contract_sha256") != expected_hash:
        raise ValueError("verification_contract_hash_mismatch")
    return {**unsigned, "contract_sha256": expected_hash}


def is_generated_backlog_ticket(markdown: str) -> bool:
    return any(
        marker in markdown
        for marker in (_GENERATED_TICKET_MARKER, _LEGACY_GENERATED_TICKET_MARKER)
    )


__all__ = [
    "canonical_plan_markdown",
    "canonical_plan_sha256",
    "canonical_ticket_body",
    "canonical_ticket_body_sha256",
    "is_generated_backlog_ticket",
    "normalize_verification_commands",
    "normalize_outcome_role_contracts",
    "parse_verification_contract_markdown",
    "render_verification_contract_markdown",
    "sha256_file",
    "sha256_text",
    "verification_commands_sha256",
    "verification_contract_payload",
]
