from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from run_artifacts import (
    COMMAND_STREAM_PREDICATE_TYPES,
    normalize_command_stream_predicate,
)

_GENERATED_TICKET_MARKER = (
    "Generated by `python -m usertest_backlog.cli reports export-tickets`"
)
_LEGACY_GENERATED_TICKET_MARKER = (
    "Generated by `python -m usertest.cli reports export-tickets`"
)
_OUTCOME_BLOCK_RE = re.compile(
    r"\n?<!-- backlog-outcome:start -->.*?<!-- backlog-outcome:end -->\n?",
    flags=re.DOTALL,
)
_VERIFICATION_CONTRACT_RE = re.compile(
    r"<!-- backlog-verification-contract:start -->\s*"
    r"```json\s*(?P<payload>\{.*?\})\s*```\s*"
    r"<!-- backlog-verification-contract:end -->",
    flags=re.DOTALL,
)
_OUTCOME_ROLES = (
    "original_scenario",
    "live",
    "mitigation_effect",
    "recurrence",
)
_CENTRALIZED_RECURRENCE_OWNER = "centralized_case_refresh"


def _canonical_json(value: Any) -> str:
    return json.dumps(
        value,
        sort_keys=True,
        ensure_ascii=False,
        separators=(",", ":"),
    )


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _normalize_markdown(value: str) -> str:
    # Outcome lifecycle writers historically decoded raw Windows bytes and then
    # wrote them through newline translation again.  Each update could therefore
    # turn CRLF into CRCRLF (and later CRCRCRLF).  Treat one-or-more carriage
    # returns immediately before LF as the same single line ending while retaining
    # normal support for lone-CR text.
    normalized = re.sub(r"\r+\n", "\n", value).replace("\r", "\n")
    return normalized.rstrip() + "\n"


def canonical_plan_markdown(markdown: str) -> str:
    """Return the immutable plan portion used for provenance hashing.

    Outcome records and the legacy source-ticket pointer are lifecycle metadata;
    moving a plan to another queue or appending an outcome must not invalidate
    the implementation provenance captured when the plan was selected.
    """

    without_outcome = _OUTCOME_BLOCK_RE.sub("\n", markdown)
    without_legacy_source = re.sub(
        r"(?m)^-\s*Source ticket:\s*`[^`]*`\s*$\n?",
        "",
        without_outcome,
    )
    return _normalize_markdown(without_legacy_source)


def canonical_ticket_body(markdown: str) -> str:
    """Return the exported issue body embedded in a generated local plan.

    Generated queue files wrap the exported body in a title, timestamp, routing
    metadata, and (optionally) a UX-review preface. This projection removes only
    that generated wrapper so the JSON export and referenced local plan can be
    compared byte-for-byte after newline normalization.
    """

    plan = canonical_plan_markdown(markdown)
    lines = plan.splitlines()
    marker_indexes = [
        index for index, line in enumerate(lines) if _GENERATED_TICKET_MARKER in line
    ]
    if not marker_indexes:
        return plan
    if len(marker_indexes) != 1:
        raise ValueError("ticket_provenance_generated_marker_ambiguous")

    marker_index = marker_indexes[0]
    heading_index: int | None = None
    for index in range(marker_index - 1, -1, -1):
        if not lines[index].strip():
            continue
        if lines[index].startswith("# "):
            heading_index = index
            break
        raise ValueError("ticket_provenance_generated_heading_invalid")
    if heading_index is None:
        raise ValueError("ticket_provenance_generated_heading_missing")

    body_index: int | None = None
    for index in range(marker_index + 1, len(lines)):
        if not lines[index].strip():
            body_index = index + 1
            break
    if body_index is None or body_index >= len(lines):
        raise ValueError("ticket_provenance_generated_body_missing")

    prefix = "\n".join(lines[:heading_index]).strip()
    body = "\n".join(lines[body_index:]).strip()
    if not body:
        raise ValueError("ticket_provenance_generated_body_empty")
    combined = f"{prefix}\n\n{body}" if prefix else body
    return _normalize_markdown(combined)


def canonical_plan_sha256(markdown: str) -> str:
    return sha256_text(canonical_plan_markdown(markdown))


def canonical_ticket_body_sha256(markdown: str) -> str:
    return sha256_text(canonical_ticket_body(markdown))


def normalize_verification_commands(commands: Sequence[str]) -> list[str]:
    normalized: list[str] = []
    for index, command in enumerate(commands):
        if not isinstance(command, str) or not command.strip():
            raise ValueError(
                f"verification_contract_command_invalid: commands[{index}]"
            )
        normalized.append(command.strip())
    if not normalized:
        raise ValueError("verification_contract_commands_empty")
    if len(normalized) != len(set(normalized)):
        raise ValueError("verification_contract_commands_duplicate")
    return normalized


def verification_commands_sha256(commands: Sequence[str]) -> str:
    normalized = normalize_verification_commands(commands)
    return sha256_text(
        _canonical_json({"schema_version": 1, "commands": normalized})
    )


def _normalize_role_predicate(
    raw: Any,
    *,
    role: str,
    index: int,
    command_count: int,
    oracle_target_ids: set[str] | None = None,
    oracle_scenario_ids: list[str] | None = None,
    causal_proofs: dict[str, dict[str, Any]] | None = None,
) -> dict[str, Any]:
    if not isinstance(raw, dict):
        raise ValueError(f"outcome_role_predicate_invalid: {role}[{index}]")
    predicate_type = raw.get("type")
    if predicate_type == "command_exit_code":
        allowed = {"type", "command_index", "equals"}
        command_index = raw.get("command_index")
        equals = raw.get("equals")
        if (
            isinstance(command_index, bool)
            or not isinstance(command_index, int)
            or command_index < 0
            or command_index >= command_count
            or isinstance(equals, bool)
            or not isinstance(equals, int)
        ):
            raise ValueError(f"outcome_role_exit_predicate_invalid: {role}[{index}]")
        normalized = {
            "type": predicate_type,
            "command_index": command_index,
            "equals": equals,
        }
    elif predicate_type in COMMAND_STREAM_PREDICATE_TYPES:
        allowed = {"type", "command_index", "value"}
        try:
            normalized = normalize_command_stream_predicate(
                raw,
                command_count=command_count,
            )
        except ValueError as exc:
            raise ValueError(
                f"outcome_role_stream_predicate_invalid: {role}[{index}]:{exc}"
            ) from exc
    elif predicate_type == "artifact_json_value":
        allowed = {"type", "path", "json_pointer", "equals"}
        path_raw = raw.get("path")
        pointer = raw.get("json_pointer")
        if not isinstance(path_raw, str) or not path_raw.strip():
            raise ValueError(f"outcome_role_artifact_path_invalid: {role}[{index}]")
        path = Path(path_raw.strip())
        if path.is_absolute() or ".." in path.parts:
            raise ValueError(f"outcome_role_artifact_path_unsafe: {role}[{index}]")
        if not isinstance(pointer, str) or (pointer and not pointer.startswith("/")):
            raise ValueError(f"outcome_role_json_pointer_invalid: {role}[{index}]")
        normalized = {
            "type": predicate_type,
            "path": path.as_posix(),
            "json_pointer": pointer,
            "equals": raw.get("equals"),
        }
    elif predicate_type == "oracle_state_equals":
        allowed = {"type", "target_id", "exists", "equals"}
        target_id = raw.get("target_id")
        exists = raw.get("exists")
        if (
            not isinstance(target_id, str)
            or not target_id.strip()
            or target_id not in (oracle_target_ids or set())
            or not isinstance(exists, bool)
            or "equals" not in raw
        ):
            raise ValueError(f"outcome_role_state_predicate_invalid: {role}[{index}]")
        normalized = {
            "type": predicate_type,
            "target_id": target_id.strip(),
            "exists": exists,
            "equals": raw.get("equals"),
        }
    elif predicate_type == "oracle_scenario_passed":
        allowed = {"type", "scenario_index", "scenario_id"}
        scenario_index = raw.get("scenario_index")
        scenario_id = raw.get("scenario_id")
        if (
            isinstance(scenario_index, bool)
            or not isinstance(scenario_index, int)
            or scenario_index < 0
            or not isinstance(oracle_scenario_ids, list)
            or scenario_index >= len(oracle_scenario_ids)
            or not isinstance(scenario_id, str)
            or scenario_id != oracle_scenario_ids[scenario_index]
        ):
            raise ValueError(f"outcome_role_scenario_predicate_invalid: {role}[{index}]")
        normalized = {
            "type": predicate_type,
            "scenario_index": scenario_index,
            "scenario_id": scenario_id,
        }
    elif predicate_type == "causal_proof_predicate":
        allowed = {
            "type",
            "proof_receipt_id",
            "intervention_id",
            "adapter_id",
            "adapter_version",
            "predicate",
            "observation_source",
            "positive_basis_sha256",
        }
        proof_id = raw.get("proof_receipt_id")
        proof = causal_proofs.get(proof_id) if isinstance(causal_proofs, dict) else None
        positive = proof.get("positive_outcome") if isinstance(proof, dict) else None
        source_root = proof.get("source_root") if isinstance(proof, dict) else None
        basis = source_root.get("positive_basis") if isinstance(source_root, dict) else None
        expected = {
            "type": "causal_proof_predicate",
            "proof_receipt_id": proof_id,
            "intervention_id": proof.get("intervention_id") if isinstance(proof, dict) else None,
            "adapter_id": proof.get("adapter_id") if isinstance(proof, dict) else None,
            "adapter_version": proof.get("adapter_version") if isinstance(proof, dict) else None,
            "predicate": positive.get("predicate") if isinstance(positive, dict) else None,
            "observation_source": (
                positive.get("observation_source") if isinstance(positive, dict) else None
            ),
            "positive_basis_sha256": (
                basis.get("basis_sha256") if isinstance(basis, dict) else None
            ),
        }
        if not isinstance(proof, dict) or raw != expected:
            raise ValueError(f"outcome_role_causal_predicate_invalid: {role}[{index}]")
        normalized = dict(raw)
    else:
        raise ValueError(f"outcome_role_predicate_type_invalid: {role}[{index}]")
    unknown = sorted(set(raw) - allowed)
    if unknown:
        raise ValueError(f"outcome_role_predicate_unknown_fields: {role}[{index}]: {unknown!r}")
    return normalized


def _normalize_causal_proof_receipts(raw: Any) -> dict[str, dict[str, Any]]:
    if not isinstance(raw, list) or not raw:
        raise ValueError("outcome_role_causal_proof_receipts_invalid")
    normalized: dict[str, dict[str, Any]] = {}
    for index, receipt in enumerate(raw):
        if not isinstance(receipt, dict):
            raise ValueError(f"outcome_role_causal_proof_receipt_invalid:{index}")
        proof_id = receipt.get("proof_receipt_id")
        projection = {
            key: value for key, value in receipt.items() if key != "proof_receipt_id"
        }
        replay = receipt.get("replay_observation")
        replay_projection = (
            {
                key: value
                for key, value in replay.items()
                if key != "replay_observation_sha256"
            }
            if isinstance(replay, dict)
            else {}
        )
        if (
            not isinstance(proof_id, str)
            or proof_id != f"causal_proof:{sha256_text(_canonical_json(projection))}"
            or proof_id in normalized
            or not isinstance(receipt.get("adapter_id"), str)
            or not isinstance(receipt.get("adapter_version"), str)
            or not isinstance(receipt.get("intervention_id"), str)
            or not isinstance(receipt.get("positive_outcome"), dict)
            or not isinstance(receipt.get("source_root"), dict)
            or not isinstance(replay, dict)
            or replay.get("runner_attested") is not True
            or replay.get("replay_observation_sha256")
            != sha256_text(_canonical_json(replay_projection))
        ):
            raise ValueError(f"outcome_role_causal_proof_receipt_invalid:{index}")
        normalized[proof_id] = dict(receipt)
    return normalized


def _validated_stage5_outcome_contract(raw: Any) -> dict[str, Any] | None:
    if not isinstance(raw, dict):
        return None
    contract_id = raw.get("outcome_contract_id")
    projection = {
        key: value for key, value in raw.items() if key != "outcome_contract_id"
    }
    if (
        contract_id
        != f"stage5_outcome_contract:{sha256_text(_canonical_json(projection))}"
        or raw.get("kind") != "selected_option_outcome_strategy"
        or raw.get("outcome_contract_status") != "approved_for_planning"
        or raw.get("post_change_evidence_status") != "unverified"
        or not isinstance(raw.get("strategy"), dict)
        or not isinstance(raw.get("review"), dict)
    ):
        return None
    return dict(raw)


def _is_fail_first_planned_replay(raw: Any) -> bool:
    if (
        not isinstance(raw, dict)
        or raw.get("kind") != "staged_replay"
        or raw.get("scenario_kind") != "fail_first_contract"
        or raw.get("positive_outcome_contracts") not in (None, [])
        or _validated_stage5_outcome_contract(raw.get("selected_outcome_contract"))
        is None
    ):
        return False
    baseline = raw.get("baseline")
    baseline_exit = baseline.get("exit_code") if isinstance(baseline, dict) else None
    if not (
        isinstance(baseline_exit, int)
        and not isinstance(baseline_exit, bool)
        and baseline_exit != 0
    ):
        return False
    return _valid_retained_stage3_fail_first_source(raw)


def _valid_retained_stage3_fail_first_source(raw: dict[str, Any]) -> bool:
    """Validate an optional reversible Stage-3 provenance envelope.

    Older exported fail-first plans predate this envelope and remain readable.  New
    bridges retain the exact content-addressed Stage-3 oracle so baseline semantics can
    be authenticated without making them active post-change outcome contracts.
    """

    retained = raw.get("retained_stage3_oracle")
    source_ref = raw.get("stage5_fail_first_source")
    if retained is None and source_ref is None:
        return True
    if not isinstance(retained, dict) or not isinstance(source_ref, dict):
        return False
    if (
        retained.get("retained_stage3_oracle") is not None
        or retained.get("stage5_fail_first_source") is not None
        or retained.get("selected_outcome_contract") is not None
    ):
        return False
    retained_id = retained.get("outcome_oracle_id")
    retained_projection = {
        key: value for key, value in retained.items() if key != "outcome_oracle_id"
    }
    retained_scenario = retained.get("scenario_kind")
    retained_baseline = retained.get("baseline")
    retained_exit = (
        retained_baseline.get("exit_code")
        if isinstance(retained_baseline, dict)
        else None
    )
    if (
        retained_id != f"outcome_oracle:{sha256_text(_canonical_json(retained_projection))}"
        or retained.get("schema_version") != 1
        or retained.get("kind") != "staged_replay"
        or retained.get("proof_scope") != "behavioral"
        or retained_scenario
        not in {
            "original_replay",
            "faithful_replay",
            "live_runtime",
            "fail_first_contract",
        }
        or isinstance(retained_exit, bool)
        or not isinstance(retained_exit, int)
        or retained_exit == 0
    ):
        return False
    retained_contracts_raw = retained.get("positive_outcome_contracts")
    if retained_contracts_raw is None:
        retained_contracts: list[dict[str, Any]] = []
    elif isinstance(retained_contracts_raw, list) and all(
        isinstance(value, dict) for value in retained_contracts_raw
    ):
        retained_contracts = retained_contracts_raw
    else:
        return False
    if retained_scenario == "fail_first_contract" and retained_contracts:
        return False
    retained_contract_ids = [
        str(contract["positive_outcome_contract_id"])
        for contract in retained_contracts
        if isinstance(contract.get("positive_outcome_contract_id"), str)
        and contract["positive_outcome_contract_id"]
    ]
    if (
        len(retained_contract_ids) != len(retained_contracts)
        or len(retained_contract_ids) != len(set(retained_contract_ids))
    ):
        return False
    for contract in retained_contracts:
        contract_id = contract.get("positive_outcome_contract_id")
        contract_projection = {
            key: value
            for key, value in contract.items()
            if key != "positive_outcome_contract_id"
        }
        postconditions = contract.get("postconditions")
        if (
            contract_id
            != f"positive_outcome_contract:{sha256_text(_canonical_json(contract_projection))}"
            or contract.get("kind")
            not in {
                "repository_test_assertion",
                "retained_research_harness_assertion",
                "origin_evidence_semantic_contract",
                "causal_proof_predicate",
            }
            or not isinstance(postconditions, list)
            or not postconditions
            or any(not isinstance(value, dict) for value in postconditions)
        ):
            return False
    retained_contract_ids.sort()
    if source_ref != {
        "schema_version": 1,
        "kind": "verified_stage3_fail_first_source",
        "source_outcome_oracle_id": retained_id,
        "source_scenario_kind": retained_scenario,
        "source_positive_outcome_contract_ids": retained_contract_ids,
    }:
        return False
    source_reversible = {
        key: value
        for key, value in retained.items()
        if key not in {"outcome_oracle_id", "positive_outcome_contracts", "scenario_kind"}
    }
    derived_reversible = {
        key: value
        for key, value in raw.items()
        if key
        not in {
            "outcome_oracle_id",
            "positive_outcome_contracts",
            "scenario_kind",
            "selected_outcome_contract",
            "retained_stage3_oracle",
            "stage5_fail_first_source",
        }
    }
    if source_reversible != derived_reversible:
        return False
    if retained_contracts:
        try:
            _normalize_outcome_oracle(retained)
        except ValueError:
            return False
    return True


def _normalize_outcome_oracle(raw: Any) -> dict[str, Any]:
    if not isinstance(raw, dict):
        raise ValueError("outcome_role_oracle_invalid")
    oracle_id = raw.get("outcome_oracle_id")
    projection = {key: value for key, value in raw.items() if key != "outcome_oracle_id"}
    expected_id = f"outcome_oracle:{sha256_text(_canonical_json(projection))}"
    if oracle_id != expected_id or raw.get("schema_version") != 1:
        raise ValueError("outcome_role_oracle_hash_invalid")
    kind = raw.get("kind")
    proof_scope = raw.get("proof_scope")
    if kind == "stage5_planned_outcome":
        if (
            proof_scope != "planned_post_change_verification"
            or raw.get("positive_outcome_contracts") not in (None, [])
            or _validated_stage5_outcome_contract(
                raw.get("selected_outcome_contract")
            )
            is None
        ):
            raise ValueError("outcome_role_stage5_planned_oracle_invalid")
    elif kind in {"staged_replay", "causal_proof_replay"}:
        if raw.get("scenario_kind") == "fail_first_contract" and not (
            kind == "staged_replay" and _is_fail_first_planned_replay(raw)
        ):
            raise ValueError("outcome_role_fail_first_planned_oracle_invalid")
        if (
            raw.get("scenario_kind") != "fail_first_contract"
            and raw.get("selected_outcome_contract") is not None
        ):
            raise ValueError("outcome_role_selected_outcome_contract_unexpected")
        execution = raw.get("execution")
        argv = execution.get("argv") if isinstance(execution, dict) else None
        authorization = (
            execution.get("command_authorization")
            if isinstance(execution, dict)
            else None
        )
        if (
            proof_scope
            != (
                "behavioral"
                if kind == "staged_replay"
                else "adapter_causal_behavior"
            )
            or not isinstance(execution, dict)
            or execution.get("shell") is not False
            or not isinstance(argv, list)
            or not argv
            or not isinstance(authorization, dict)
            or not isinstance(authorization.get("authorization_kind"), str)
            or not authorization.get("authorization_kind", "").strip()
            or authorization.get("executed_argv_sha256")
            != sha256_text(_canonical_json(argv))
            or authorization.get("shell") is not False
            or authorization.get("workspace_confined") is not True
        ):
            raise ValueError("outcome_role_replay_oracle_invalid")
        if kind == "causal_proof_replay":
            proof_ids = raw.get("proof_receipt_ids")
            setup = execution.get("replay_setup_receipt")
            setup_reference = execution.get("replay_setup_reference")
            setup_projection = (
                {
                    key: value
                    for key, value in setup.items()
                    if key != "replay_setup_sha256"
                }
                if isinstance(setup, dict)
                else {}
            )
            if (
                not isinstance(proof_ids, list)
                or not proof_ids
                or proof_ids != sorted(set(proof_ids))
                or not isinstance(setup, dict)
                or setup.get("runner_applied") is not True
                or setup.get("replay_setup_sha256")
                != sha256_text(_canonical_json(setup_projection))
                or not isinstance(setup_reference, dict)
                or setup_reference.get("source") != "research_experiment"
                or setup_reference.get("experiment_id")
                != raw.get("research_experiment_id")
                or not isinstance(setup_reference.get("replay_setup_sha256"), str)
                or re.fullmatch(
                    r"[0-9a-f]{64}",
                    str(setup_reference.get("replay_setup_sha256")),
                )
                is None
            ):
                raise ValueError("outcome_role_causal_replay_oracle_invalid")
    elif kind == "config_state":
        targets = raw.get("state_targets")
        if proof_scope != "configuration_state" or not isinstance(targets, list) or not targets:
            raise ValueError("outcome_role_config_oracle_invalid")
    elif kind == "multi_scenario":
        scenarios = raw.get("scenarios")
        contracts = raw.get("positive_outcome_contracts")
        contract_ids = {
            contract.get("positive_outcome_contract_id")
            for contract in contracts if isinstance(contract, dict)
        } if isinstance(contracts, list) else set()
        if (
            proof_scope != "multi_scenario"
            or not isinstance(scenarios, list)
            or len(scenarios) < 2
            or not contract_ids
        ):
            raise ValueError("outcome_role_multi_scenario_oracle_invalid")
        observed_ids: set[str] = set()
        for index, scenario in enumerate(scenarios):
            if not isinstance(scenario, dict):
                raise ValueError(f"outcome_role_multi_scenario_invalid:{index}")
            scenario_id = scenario.get("scenario_id")
            scenario_projection = {
                key: value for key, value in scenario.items() if key != "scenario_id"
            }
            selected_id = scenario.get("positive_outcome_contract_id")
            child = _normalize_outcome_oracle(scenario.get("oracle"))
            child_contracts = child.get("positive_outcome_contracts")
            child_ids = {
                contract.get("positive_outcome_contract_id")
                for contract in child_contracts if isinstance(contract, dict)
            } if isinstance(child_contracts, list) else set()
            predicates = scenario.get("predicates")
            if (
                scenario_id
                != f"outcome_scenario:{sha256_text(_canonical_json(scenario_projection))}"
                or child.get("kind") == "multi_scenario"
                or selected_id not in contract_ids
                or selected_id not in child_ids
                or selected_id in observed_ids
                or not isinstance(predicates, list)
                or not predicates
            ):
                raise ValueError(f"outcome_role_multi_scenario_invalid:{index}")
            observed_ids.add(str(selected_id))
        if observed_ids != contract_ids:
            raise ValueError("outcome_role_multi_scenario_contract_coverage_invalid")
    else:
        raise ValueError("outcome_role_oracle_kind_invalid")
    return dict(raw)


def normalize_outcome_role_contracts(
    raw: Any,
    *,
    test_commands: Sequence[str],
) -> dict[str, dict[str, Any] | None]:
    """Normalize role-specific, machine-evaluated post-merge proof contracts."""

    if not isinstance(raw, dict):
        raise ValueError("outcome_role_contracts_invalid")
    missing = sorted(set(_OUTCOME_ROLES) - set(raw))
    unknown = sorted(set(raw) - set(_OUTCOME_ROLES))
    if missing or unknown:
        raise ValueError(
            f"outcome_role_contract_fields_invalid: missing={missing!r} unknown={unknown!r}"
        )
    generic_commands = set(normalize_verification_commands(test_commands))
    original_raw = raw.get("original_scenario")
    original_oracle_raw = (
        original_raw.get("oracle") if isinstance(original_raw, dict) else None
    )
    fail_first_planned_replay = _is_fail_first_planned_replay(original_oracle_raw)
    selected_outcome_contract_raw = (
        original_oracle_raw.get("selected_outcome_contract")
        if isinstance(original_oracle_raw, dict)
        and (
            original_oracle_raw.get("kind") == "stage5_planned_outcome"
            or fail_first_planned_replay
        )
        else None
    )
    selected_outcome_contract = _validated_stage5_outcome_contract(
        selected_outcome_contract_raw
    )
    planned_outcome_contract_id = (
        selected_outcome_contract.get("outcome_contract_id")
        if selected_outcome_contract is not None
        else None
    )
    planned_repo_revision = (
        original_oracle_raw.get("repo_revision")
        if isinstance(original_oracle_raw, dict)
        else None
    )
    normalized: dict[str, dict[str, Any] | None] = {}
    for role in _OUTCOME_ROLES:
        value = raw.get(role)
        if value is None:
            normalized[role] = None
            continue
        if not isinstance(value, dict):
            raise ValueError(f"outcome_role_contract_invalid: {role}")
        allowed = {
            "description",
            "commands",
            "predicates",
            "research_experiment_id",
            "research_experiment_ids",
            "selected_positive_outcome_contract_ids",
            "oracle",
            "required_proof_scope",
            "causal_proof_receipts",
            "command_bindings",
            "execution_status",
            "verification_owner",
            "role_contract_sha256",
        }
        unknown_fields = sorted(set(value) - allowed)
        if unknown_fields:
            raise ValueError(
                f"outcome_role_contract_unknown_fields: {role}: {unknown_fields!r}"
            )
        description = value.get("description")
        if not isinstance(description, str) or not description.strip():
            raise ValueError(f"outcome_role_description_invalid: {role}")
        oracle_raw = value.get("oracle")
        if oracle_raw is not None and role != "original_scenario":
            raise ValueError(f"outcome_role_oracle_forbidden: {role}")
        oracle = _normalize_outcome_oracle(oracle_raw) if oracle_raw is not None else None
        oracle_kind = oracle.get("kind") if oracle is not None else None
        verification_owner = value.get("verification_owner")
        centralized_recurrence = (
            role == "recurrence"
            and verification_owner == _CENTRALIZED_RECURRENCE_OWNER
        )
        if verification_owner is not None and not centralized_recurrence:
            raise ValueError(f"outcome_role_verification_owner_invalid: {role}")
        proof_scope = value.get("required_proof_scope")
        if oracle is not None and proof_scope != oracle.get("proof_scope"):
            raise ValueError("outcome_role_oracle_scope_mismatch")
        if oracle is None and proof_scope is not None:
            raise ValueError(f"outcome_role_scope_without_oracle: {role}")
        commands_raw = value.get("commands")
        if not isinstance(commands_raw, list):
            raise ValueError(f"outcome_role_commands_invalid: {role}")
        if oracle is not None and oracle_kind != "stage5_planned_outcome":
            if commands_raw:
                raise ValueError("outcome_role_oracle_commands_forbidden")
            commands = []
        elif centralized_recurrence and not commands_raw:
            commands = []
        else:
            commands = normalize_verification_commands(commands_raw)
        if centralized_recurrence and commands:
            raise ValueError("outcome_role_centralized_recurrence_commands_invalid")
        if role in {"live", "mitigation_effect", "recurrence"}:
            if generic_commands.intersection(commands):
                raise ValueError(f"outcome_role_generic_command_reused: {role}")
            bindings_raw = value.get("command_bindings")
            if commands:
                if not isinstance(bindings_raw, list):
                    raise ValueError(f"outcome_role_command_bindings_invalid: {role}")
                bound_indices: set[int] = set()
                planned_binding_indices: set[int] = set()
                normalized_bindings: list[dict[str, Any]] = []
                for binding_index, binding in enumerate(bindings_raw):
                    if not isinstance(binding, dict):
                        raise ValueError(
                            f"outcome_role_command_binding_invalid:{role}:{binding_index}"
                        )
                    command_index = binding.get("command_index")
                    experiment_id = binding.get("research_experiment_id")
                    index_invalid = bool(
                        isinstance(command_index, bool)
                        or not isinstance(command_index, int)
                        or command_index < 0
                        or command_index >= len(commands)
                        or command_index in bound_indices
                    )
                    if index_invalid:
                        raise ValueError(
                            f"outcome_role_command_binding_invalid:{role}:{binding_index}"
                        )
                    assert isinstance(command_index, int)
                    if binding.get("binding_kind") == "stage6_planned_post_change":
                        selected_contract_id = binding.get(
                            "selected_outcome_contract_id"
                        )
                        repo_revision = binding.get("repo_revision")
                        if (
                            role not in {"live", "mitigation_effect"}
                            or set(binding)
                            != {
                                "command_index",
                                "binding_kind",
                                "selected_outcome_contract_id",
                                "repo_revision",
                            }
                            or not isinstance(selected_contract_id, str)
                            or not selected_contract_id.strip()
                            or selected_contract_id.strip()
                            != planned_outcome_contract_id
                            or not isinstance(repo_revision, str)
                            or not repo_revision.strip()
                            or repo_revision.strip() != planned_repo_revision
                        ):
                            raise ValueError(
                                "outcome_role_planned_command_binding_invalid:"
                                f"{role}:{binding_index}"
                            )
                        bound_indices.add(command_index)
                        planned_binding_indices.add(command_index)
                        normalized_bindings.append(
                            {
                                "command_index": command_index,
                                "binding_kind": "stage6_planned_post_change",
                                "selected_outcome_contract_id": (
                                    selected_contract_id.strip()
                                ),
                                "repo_revision": repo_revision.strip(),
                            }
                        )
                        continue
                    if (
                        not isinstance(experiment_id, str)
                        or not experiment_id.strip()
                        or set(binding) != {"command_index", "research_experiment_id"}
                    ):
                        raise ValueError(
                            f"outcome_role_command_binding_invalid:{role}:{binding_index}"
                        )
                    bound_indices.add(command_index)
                    normalized_bindings.append(
                        {
                            "command_index": command_index,
                            "research_experiment_id": experiment_id.strip(),
                        }
                    )
                if bound_indices != set(range(len(commands))):
                    raise ValueError(
                        f"outcome_role_command_binding_coverage_invalid:{role}"
                    )
                if planned_binding_indices:
                    if value.get("execution_status") != "planned_unverified":
                        raise ValueError(
                            f"outcome_role_planned_execution_status_invalid:{role}"
                        )
                elif value.get("execution_status") is not None:
                    raise ValueError(
                        f"outcome_role_execution_status_unexpected:{role}"
                    )
            elif bindings_raw not in (None, []):
                raise ValueError(f"outcome_role_command_bindings_without_commands:{role}")
            else:
                normalized_bindings = []
                if value.get("execution_status") is not None:
                    raise ValueError(
                        f"outcome_role_execution_status_unexpected:{role}"
                    )
        else:
            if value.get("command_bindings") not in (None, []):
                raise ValueError(f"outcome_role_command_bindings_forbidden:{role}")
            if value.get("execution_status") is not None:
                raise ValueError(f"outcome_role_execution_status_forbidden:{role}")
            normalized_bindings = []
        predicates_raw = value.get("predicates")
        if not isinstance(predicates_raw, list) or (
            not predicates_raw and not centralized_recurrence
        ):
            raise ValueError(f"outcome_role_predicates_invalid: {role}")
        if centralized_recurrence and predicates_raw:
            raise ValueError("outcome_role_centralized_recurrence_predicates_invalid")
        oracle_target_ids = {
            str(target.get("target_id"))
            for target in (oracle.get("state_targets", []) if oracle is not None else [])
            if isinstance(target, dict) and isinstance(target.get("target_id"), str)
        }
        oracle_scenario_ids = [
            str(scenario.get("scenario_id"))
            for scenario in (oracle.get("scenarios", []) if oracle is not None else [])
            if isinstance(scenario, dict) and isinstance(scenario.get("scenario_id"), str)
        ]
        causal_proofs = (
            _normalize_causal_proof_receipts(value.get("causal_proof_receipts"))
            if oracle_kind == "causal_proof_replay"
            else {}
        )
        if oracle_kind == "causal_proof_replay" and set(causal_proofs) != set(
            oracle.get("proof_receipt_ids", [])
        ):
            raise ValueError("outcome_role_causal_proof_receipt_coverage_invalid")
        if oracle_kind != "causal_proof_replay" and value.get(
            "causal_proof_receipts"
        ) not in (None, []):
            raise ValueError("outcome_role_causal_proof_receipts_unexpected")
        command_count = (
            1
            if oracle_kind in {"staged_replay", "causal_proof_replay"}
            else len(commands)
        )
        predicates = [
            _normalize_role_predicate(
                predicate,
                role=role,
                index=index,
                command_count=command_count,
                oracle_target_ids=oracle_target_ids,
                oracle_scenario_ids=oracle_scenario_ids,
                causal_proofs=causal_proofs,
            )
            for index, predicate in enumerate(predicates_raw)
        ]
        exit_covered = {
            predicate["command_index"]
            for predicate in predicates
            if predicate["type"] == "command_exit_code"
        }
        expected_exit_covered = {0} if oracle_kind == "staged_replay" else set(range(len(commands)))
        if exit_covered != expected_exit_covered:
            raise ValueError(f"outcome_role_exit_predicate_coverage_invalid: {role}")
        if oracle_kind == "config_state":
            state_covered = {
                predicate["target_id"]
                for predicate in predicates
                if predicate["type"] == "oracle_state_equals"
            }
            if state_covered != oracle_target_ids:
                raise ValueError("outcome_role_state_predicate_coverage_invalid")
        if oracle_kind == "multi_scenario":
            scenario_covered = [
                predicate["scenario_id"]
                for predicate in predicates
                if predicate["type"] == "oracle_scenario_passed"
            ]
            if scenario_covered != oracle_scenario_ids:
                raise ValueError("outcome_role_scenario_predicate_coverage_invalid")
        research_experiment_id = value.get("research_experiment_id")
        research_experiment_ids = value.get("research_experiment_ids")
        selected_contract_ids = value.get("selected_positive_outcome_contract_ids")
        if role == "original_scenario":
            if not isinstance(research_experiment_id, str) or not research_experiment_id.strip():
                raise ValueError("outcome_role_research_experiment_id_required")
            if (
                oracle is not None
                and oracle_kind != "multi_scenario"
                and oracle.get("research_experiment_id") != (
                research_experiment_id.strip()
                )
            ):
                raise ValueError("outcome_role_oracle_experiment_mismatch")
            normalized_experiment_ids = (
                research_experiment_ids
                if isinstance(research_experiment_ids, list)
                else [research_experiment_id.strip()]
            )
            if (
                not normalized_experiment_ids
                or any(
                    not isinstance(value, str) or not value.strip()
                    for value in normalized_experiment_ids
                )
                or normalized_experiment_ids[0] != research_experiment_id.strip()
            ):
                raise ValueError("outcome_role_research_experiment_ids_invalid")
            oracle_contract_ids = {
                contract.get("positive_outcome_contract_id")
                for contract in (
                    oracle.get("positive_outcome_contracts", [])
                    if isinstance(oracle, dict)
                    else []
                )
                if isinstance(contract, dict)
            }
            normalized_selected_ids = (
                selected_contract_ids
                if isinstance(selected_contract_ids, list)
                else list(oracle_contract_ids)
                if len(oracle_contract_ids) == 1
                else []
            )
            planned_or_fail_first_oracle = bool(
                oracle_kind == "stage5_planned_outcome"
                or _is_fail_first_planned_replay(oracle)
            )
            if oracle is not None and not planned_or_fail_first_oracle and (
                not normalized_selected_ids
                or len(normalized_selected_ids) != len(set(normalized_selected_ids))
                or any(value not in oracle_contract_ids for value in normalized_selected_ids)
                or (
                    oracle_kind == "multi_scenario"
                    and set(normalized_selected_ids) != oracle_contract_ids
                )
                or (
                    oracle_kind != "multi_scenario"
                    and len(normalized_selected_ids) != 1
                )
            ):
                raise ValueError("outcome_role_selected_positive_contract_ids_invalid")
            if planned_or_fail_first_oracle and selected_contract_ids not in (None, []):
                raise ValueError(
                    "outcome_role_selected_positive_contract_unexpected_for_planned_outcome"
                )
            if oracle is None and selected_contract_ids is not None:
                raise ValueError("outcome_role_selected_positive_contract_without_oracle")
        elif research_experiment_id is not None:
            raise ValueError(f"outcome_role_research_experiment_id_forbidden: {role}")
        elif research_experiment_ids is not None or selected_contract_ids is not None:
            raise ValueError(f"outcome_role_original_scenario_fields_forbidden: {role}")
        role_payload: dict[str, Any] = {
            "description": description.strip(),
            "commands": commands,
            "predicates": predicates,
        }
        if centralized_recurrence:
            role_payload["verification_owner"] = _CENTRALIZED_RECURRENCE_OWNER
        if normalized_bindings:
            role_payload["command_bindings"] = normalized_bindings
        if value.get("execution_status") == "planned_unverified":
            role_payload["execution_status"] = "planned_unverified"
        if role == "original_scenario":
            role_payload["research_experiment_id"] = research_experiment_id.strip()
            if research_experiment_ids is not None:
                role_payload["research_experiment_ids"] = [
                    value.strip() for value in normalized_experiment_ids
                ]
            if selected_contract_ids is not None:
                role_payload["selected_positive_outcome_contract_ids"] = list(
                    normalized_selected_ids
                )
            if oracle is not None:
                role_payload["oracle"] = oracle
                role_payload["required_proof_scope"] = proof_scope
            if causal_proofs:
                role_payload["causal_proof_receipts"] = list(causal_proofs.values())
        role_hash = sha256_text(_canonical_json(role_payload))
        supplied_role_hash = value.get("role_contract_sha256")
        if supplied_role_hash is not None and supplied_role_hash != role_hash:
            raise ValueError(f"outcome_role_contract_hash_mismatch: {role}")
        normalized[role] = {**role_payload, "role_contract_sha256": role_hash}
    if normalized["original_scenario"] is None:
        raise ValueError("outcome_role_original_scenario_required")
    if normalized["recurrence"] is None:
        raise ValueError("outcome_role_recurrence_required")
    return normalized


def verification_contract_payload(
    commands: Sequence[str],
    *,
    outcome_roles: Any | None = None,
) -> dict[str, Any]:
    normalized = normalize_verification_commands(commands)
    if outcome_roles is None:
        return {
            "schema_version": 1,
            "commands": normalized,
            "contract_sha256": verification_commands_sha256(normalized),
        }
    normalized_roles = normalize_outcome_role_contracts(
        outcome_roles,
        test_commands=normalized,
    )
    unsigned = {
        "schema_version": 2,
        "commands": normalized,
        "outcome_roles": normalized_roles,
    }
    return {**unsigned, "contract_sha256": sha256_text(_canonical_json(unsigned))}


def render_verification_contract_markdown(
    commands: Sequence[str],
    *,
    outcome_roles: Any | None = None,
) -> str:
    payload = verification_contract_payload(commands, outcome_roles=outcome_roles)
    rendered = json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True)
    return (
        "<!-- backlog-verification-contract:start -->\n"
        "```json\n"
        f"{rendered}\n"
        "```\n"
        "<!-- backlog-verification-contract:end -->"
    )


def parse_verification_contract_markdown(markdown: str) -> dict[str, Any] | None:
    matches = list(_VERIFICATION_CONTRACT_RE.finditer(markdown))
    if not matches:
        return None
    if len(matches) != 1:
        raise ValueError("verification_contract_block_ambiguous")
    try:
        payload = json.loads(matches[0].group("payload"))
    except json.JSONDecodeError as exc:
        raise ValueError("verification_contract_json_invalid") from exc
    if not isinstance(payload, dict):
        raise ValueError("verification_contract_payload_invalid")
    allowed = {"schema_version", "commands", "outcome_roles", "contract_sha256"}
    unknown = sorted(set(payload) - allowed)
    if unknown:
        raise ValueError(f"verification_contract_unknown_fields: {unknown!r}")
    if payload.get("schema_version") not in {1, 2}:
        raise ValueError("verification_contract_schema_version_invalid")
    commands_raw = payload.get("commands")
    if not isinstance(commands_raw, list):
        raise ValueError("verification_contract_commands_invalid")
    commands = normalize_verification_commands(commands_raw)
    if payload.get("schema_version") == 1:
        if "outcome_roles" in payload:
            raise ValueError("verification_contract_v1_outcome_roles_forbidden")
        expected_hash = verification_commands_sha256(commands)
        if payload.get("contract_sha256") != expected_hash:
            raise ValueError("verification_contract_hash_mismatch")
        return {
            "schema_version": 1,
            "commands": commands,
            "contract_sha256": expected_hash,
        }
    roles = normalize_outcome_role_contracts(
        payload.get("outcome_roles"),
        test_commands=commands,
    )
    unsigned = {"schema_version": 2, "commands": commands, "outcome_roles": roles}
    expected_hash = sha256_text(_canonical_json(unsigned))
    if payload.get("contract_sha256") != expected_hash:
        raise ValueError("verification_contract_hash_mismatch")
    return {**unsigned, "contract_sha256": expected_hash}


def is_generated_backlog_ticket(markdown: str) -> bool:
    return any(
        marker in markdown
        for marker in (_GENERATED_TICKET_MARKER, _LEGACY_GENERATED_TICKET_MARKER)
    )


__all__ = [
    "canonical_plan_markdown",
    "canonical_plan_sha256",
    "canonical_ticket_body",
    "canonical_ticket_body_sha256",
    "is_generated_backlog_ticket",
    "normalize_verification_commands",
    "normalize_outcome_role_contracts",
    "parse_verification_contract_markdown",
    "render_verification_contract_markdown",
    "sha256_file",
    "sha256_text",
    "verification_commands_sha256",
    "verification_contract_payload",
]
