# ruff: noqa: E501,F401,F403,F405
from __future__ import annotations

from usertest_backlog.shared import *


def _ticket_requires_live_verification(ticket: dict[str, Any]) -> bool | None:
    """Return an explicitly declared live-verification requirement."""

    direct = ticket.get("requires_live_verification")
    if isinstance(direct, bool):
        return direct
    change_plan = ticket.get("change_plan")
    if isinstance(change_plan, dict):
        nested = change_plan.get("requires_live_verification")
        if isinstance(nested, bool):
            return nested
    return None


def _write_ticket_idea_file(
    *,
    ticket: dict[str, Any],
    issue_title: str,
    fingerprint: str,
    body_markdown: str,
    owner_repo_root: Path,
    scope_target: str | None = None,
    scope_repo_input: str | None = None,
    ux_review_section: str | None = None,
) -> Path:
    """
    Write a single exported ticket as a generated queue markdown file in owner repo plans.
    """
    stage = (_coerce_string(ticket.get("stage")) or "triage").strip().lower()
    queue_dir = _ticket_queue_dir_for_stage(owner_repo_root=owner_repo_root, stage=stage)
    queue_dir.mkdir(parents=True, exist_ok=True)

    date_tag = datetime.now(timezone.utc).strftime("%Y%m%d")
    title_slug = slugify(issue_title) or "untitled"
    filename = f"{date_tag}_{fingerprint}_{title_slug[:64]}.md"
    out_path = queue_dir / filename
    out_path.write_text(
        _render_ticket_idea_markdown(
            issue_title=issue_title,
            fingerprint=fingerprint,
            body_markdown=body_markdown,
            scope_target=scope_target,
            scope_repo_input=scope_repo_input,
            execution_domain=_coerce_string(ticket.get("execution_domain")),
            execution_conflict_keys=_coerce_string_list(ticket.get("execution_conflict_keys")),
            ux_review_section=ux_review_section,
            case_id=ticket_export_case_id(ticket),
            plan_revision_id=ticket_export_plan_revision_id(ticket),
            requires_live_verification=_ticket_requires_live_verification(ticket),
        ),
        encoding="utf-8",
    )
    return out_path


def _render_ticket_idea_markdown(
    *,
    issue_title: str,
    fingerprint: str,
    body_markdown: str,
    scope_target: str | None,
    scope_repo_input: str | None,
    execution_domain: str | None,
    execution_conflict_keys: list[str],
    ux_review_section: str | None,
    case_id: str | None = None,
    plan_revision_id: str | None = None,
    requires_live_verification: bool | None = None,
) -> str:
    lines: list[str] = []
    if isinstance(ux_review_section, str) and ux_review_section.strip():
        lines.append(ux_review_section.strip())
        lines.append("")
    lines.append(f"# {issue_title}")
    lines.append("")
    lines.append(
        f"Generated by `python -m usertest_backlog.cli reports export-tickets` on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}."
    )
    lines.append(f"- Fingerprint: `{fingerprint}`")
    if isinstance(case_id, str) and case_id.strip():
        lines.append(f"- Case ID: `{case_id.strip()}`")
    if isinstance(plan_revision_id, str) and plan_revision_id.strip():
        lines.append(f"- Plan revision ID: `{plan_revision_id.strip()}`")
    if isinstance(case_id, str) and case_id.strip():
        lines.append("- Outcome state: `planned`")
    if isinstance(requires_live_verification, bool):
        value = "true" if requires_live_verification else "false"
        lines.append(f"- Requires live verification: `{value}`")
    if isinstance(scope_target, str) and scope_target.strip():
        lines.append(f"- Export scope target: `{scope_target.strip()}`")
    if isinstance(scope_repo_input, str) and scope_repo_input.strip():
        lines.append(f"- Export scope repo_input: `{scope_repo_input.strip()}`")
    if isinstance(execution_domain, str) and execution_domain.strip():
        lines.append(f"- Execution domain: `{execution_domain.strip()}`")
    cleaned_conflict_keys = [value.strip() for value in execution_conflict_keys if value.strip()]
    if cleaned_conflict_keys:
        rendered_keys = ", ".join(f"`{value}`" for value in cleaned_conflict_keys)
        lines.append(f"- Execution conflict keys: {rendered_keys}")
    lines.append("")
    lines.append(body_markdown.rstrip())
    lines.append("")
    return "\n".join(lines)


def _refresh_generated_ticket_idea_file(
    *,
    path: Path,
    issue_title: str,
    fingerprint: str,
    body_markdown: str,
    scope_target: str | None,
    scope_repo_input: str | None,
    execution_domain: str | None,
    execution_conflict_keys: list[str],
    ux_review_section: str | None,
    case_id: str | None = None,
    plan_revision_id: str | None = None,
    requires_live_verification: bool | None = None,
) -> bool:
    if _extract_generated_ticket_scope_metadata(path) is None:
        return False
    path.write_text(
        _render_ticket_idea_markdown(
            issue_title=issue_title,
            fingerprint=fingerprint,
            body_markdown=body_markdown,
            scope_target=scope_target,
            scope_repo_input=scope_repo_input,
            execution_domain=execution_domain,
            execution_conflict_keys=execution_conflict_keys,
            ux_review_section=ux_review_section,
            case_id=case_id,
            plan_revision_id=plan_revision_id,
            requires_live_verification=requires_live_verification,
        ),
        encoding="utf-8",
    )
    return True


def _ticket_queue_dir_for_stage(*, owner_repo_root: Path, stage: str) -> Path:
    """Return ticket queue dir for stage data.

    Parameters
    ----------
    owner_repo_root:
        Root directory path.
    stage:
        Input parameter.

    Returns
    -------
    Path
        Resolved filesystem path value.
    """
    normalized = stage.strip().lower()
    if normalized == "triage":
        return owner_repo_root / ".agents" / "plans" / "0.5 - to_triage"
    if normalized == "ready_for_ticket":
        return owner_repo_root / ".agents" / "plans" / "2 - ready"
    return owner_repo_root / ".agents" / "plans" / "1 - ideas"


def _ticket_queue_dirs(owner_repo_root: Path) -> list[Path]:
    """Return ticket queue dirs data.

    Parameters
    ----------
    owner_repo_root:
        Root directory path.

    Returns
    -------
    list[Path]
        Normalized list result.
    """
    return [
        owner_repo_root / ".agents" / "plans" / "2 - ready",
        owner_repo_root / ".agents" / "plans" / "1 - ideas",
        owner_repo_root / ".agents" / "plans" / "0.5 - to_triage",
        # Legacy triage queue path retained for stale-file cleanup compatibility.
        owner_repo_root / ".agents" / "plans" / "1.5 - to_plan",
    ]


def _cleanup_stale_ticket_idea_files(
    *,
    ticket: dict[str, Any],
    fingerprint: str,
    owner_repo_root: Path,
    repo_root: Path,
    scope_repo_input: str | None,
    cli_repo_input: str | None,
    keep_path: Path | None = None,
) -> None:
    """
    Remove stale duplicate idea files for this ticket fingerprint from non-owner queues.
    """

    pattern = f"*_{fingerprint}_*.md"

    candidate_roots: set[Path] = {repo_root.resolve(), owner_repo_root.resolve()}
    for candidate in (
        _resolve_local_repo_input_root(repo_input=scope_repo_input, repo_root=repo_root),
        _resolve_local_repo_input_root(repo_input=cli_repo_input, repo_root=repo_root),
    ):
        if candidate is not None:
            candidate_roots.add(candidate.resolve())

    for repo_input in _coerce_string_list(ticket.get("repo_inputs_citing")):
        candidate = _resolve_local_repo_input_root(repo_input=repo_input, repo_root=repo_root)
        if candidate is not None:
            candidate_roots.add(candidate.resolve())

    keep_path_resolved = keep_path.resolve() if keep_path is not None else None
    for candidate_root in candidate_roots:
        for queue_dir in _ticket_queue_dirs(candidate_root):
            if not queue_dir.exists() or not queue_dir.is_dir():
                continue
            for stale in queue_dir.glob(pattern):
                stale_resolved = stale.resolve()
                if keep_path_resolved is not None and stale_resolved == keep_path_resolved:
                    continue
                if _extract_generated_ticket_scope_metadata(stale) is None:
                    continue
                _archive_plan_ticket_file(
                    owner_root=candidate_root,
                    path=stale,
                    disposition="duplicate",
                    related_fingerprint=fingerprint,
                    reason="Duplicate generated queue file for the same fingerprint",
                )


def _extract_generated_ticket_scope_metadata(
    path: Path,
) -> tuple[str | None, str | None, str | None, str | None] | None:
    try:
        excerpt = _read_text_excerpt(path, max_bytes=32_768)
    except OSError:
        return None

    if "Generated by `python -m usertest_backlog.cli reports export-tickets`" not in excerpt:
        return None

    fingerprint_match = re.search(r"^- Fingerprint:\s+`([^`]+)`", excerpt, flags=re.MULTILINE)
    fingerprint = fingerprint_match.group(1).strip() if fingerprint_match else None

    target_match = re.search(
        r"^- Export scope target:\s+`([^`]+)`",
        excerpt,
        flags=re.MULTILINE,
    )
    target = target_match.group(1).strip() if target_match else None

    repo_input_match = re.search(
        r"^- Export scope repo_input:\s+`([^`]+)`",
        excerpt,
        flags=re.MULTILINE,
    )
    repo_input = repo_input_match.group(1).strip() if repo_input_match else None

    case_match = re.search(r"^- Case ID:\s+`([^`]+)`", excerpt, flags=re.MULTILINE)
    case_id = case_match.group(1).strip() if case_match else None

    if target is None:
        legacy_atom_match = re.search(r"- `([^`]+/\d{8}T[^`]+)`", excerpt)
        if legacy_atom_match:
            atom_id = legacy_atom_match.group(1).strip()
            if "/" in atom_id:
                target = atom_id.split("/", 1)[0].strip() or None

    return fingerprint, target, repo_input, case_id


def _cleanup_stale_generated_scope_ticket_files(
    *,
    owner_repo_root: Path,
    target_slug: str | None,
    keep_fingerprints: set[str],
    keep_fingerprint_by_case_id: dict[str, str | None] | None = None,
) -> dict[str, int]:
    if not isinstance(target_slug, str) or not target_slug.strip():
        return {"archived": 0, "unresolved": 0}

    archived = 0
    unresolved = 0
    normalized_target = target_slug.strip()
    for queue_dir in _ticket_queue_dirs(owner_repo_root.resolve()):
        if not queue_dir.exists() or not queue_dir.is_dir():
            continue
        for candidate in queue_dir.glob("*.md"):
            metadata = _extract_generated_ticket_scope_metadata(candidate)
            if metadata is None:
                continue
            fingerprint, file_target, _repo_input, case_id = metadata
            if not fingerprint or fingerprint in keep_fingerprints:
                continue
            if file_target != normalized_target:
                continue
            replacement = (
                keep_fingerprint_by_case_id.get(case_id)
                if keep_fingerprint_by_case_id is not None and case_id is not None
                else None
            )
            if replacement is None:
                # Wording-based scope membership is not enough evidence that a
                # ticket was superseded. Preserve it until canonical lineage can
                # identify an explicit replacement.
                unresolved += 1
                continue
            _archive_plan_ticket_file(
                owner_root=owner_repo_root,
                path=candidate,
                disposition="superseded",
                related_fingerprint=replacement,
                reason="A newer plan revision for the same canonical case was exported",
            )
            archived += 1
    return {"archived": archived, "unresolved": unresolved}


def _cleanup_actioned_plan_queue_duplicates(*, owner_repo_root: Path) -> int:
    """Archive queued plan files for fingerprints already marked actioned.

    This is a best-effort hygiene sweep to eliminate stale duplicates that can
    linger across runs even when the current backlog no longer contains that
    fingerprint.

    Returns
    -------
    int
        Number of files archived with a duplicate relationship.
    """

    removed = 0
    owner_root = owner_repo_root.resolve()
    queue_dirs = {p.resolve() for p in _ticket_queue_dirs(owner_root)}
    if not queue_dirs:
        return 0

    index = _scan_plan_ticket_index(owner_root=owner_root, include_discarded=False)
    for fingerprint, meta in index.items():
        if not isinstance(meta, dict):
            continue
        if meta.get("status") != "actioned":
            continue
        paths = [item for item in meta.get("paths", []) if isinstance(item, str) and item]
        for path_s in paths:
            candidate = Path(path_s)
            try:
                candidate_parent = candidate.parent.resolve()
            except OSError:
                continue
            if candidate_parent not in queue_dirs:
                continue
            if candidate.suffix.lower() != ".md":
                continue
            if candidate.exists():
                _archive_plan_ticket_file(
                    owner_root=owner_root,
                    path=candidate,
                    disposition="duplicate",
                    related_fingerprint=fingerprint,
                    reason="Same fingerprint already exists in an actioned plan bucket",
                )
                removed += 1
    return removed


__all__ = [name for name in globals() if not name.startswith("__")]
